### ISSUE TITLE
Bug:/Enhancement:/Feature Request: Socket connection to 'wss://something.vercel.app/server/webrtc' failed:  _

### ISSUE THREAD

**Issue by iamsomeonefromsomewhere** [schlagmichdoch/PairDrop#100]
while hosting on vercel

**Comment by schlagmichdoch** [comment]
Probably webservices hosted with vercel cannot establish websocket connections which is crucial for PairDrop currently.

A quick search lead to this stackoverflow: https://stackoverflow.com/questions/65379821/cant-connect-to-websocket-server-after-pushing-to-vercel

Probably this is a constraint of vercel and not an issue with PairDrop.

In the future, please set a clearer issue title like „Bug: wss connection on vercel not working“ to make it easier to understand.
