### ISSUE TITLE
Bug: Accepting files broken under Google Chrome, due to missing Element

### ISSUE THREAD

**Issue by raceimaztion** [schlagmichdoch/PairDrop#101]
**The Problem**
Passing files from Android to PC running Google Chrome 111.0.5563.110 (Official Build) (64-bit) fails.

**To Reproduce**
Steps to reproduce the behaviour:
1. Ensure both computers involved are on the same WiFi network.
2. Both computers have one browser logged into PairDrop website.
3. From Android device (in this case), select a file to pass to the PC and send it.
4. See page title change to "Image Received", but no message box pops up to preview the image, and accept or reject it.

**Expected behaviour:**
File sharing notification should pop up, with preview and buttons for Accepting or Rejecting file.

**Screenshots**

**Desktop (receiving):**
 - OS: Ubuntu 20.04
 - Browser: Google Chrome
 - Version: 111.0.5563.110

**Smartphone (please complete the following information):**
 - Device: LG G7
 - OS: Android 9
 - Browser: Google Chrome
 - Version: 111.0.5563.116

**Self-Hosted**
No

**Addition Information:**
System breaks due to an attempt to change an Element that does not exist. Line 2036 of ui.js attempts to change an element where `rel="icon"`, but since no such element exists, and no error checking is performed, the whole event crashes out and fails to progress through the process.

Commenting out the line in-browser (Chrome is quite useful this way) allowed me to accept the transferred file, and showed no other errors that I was able to find.

**Comment by schlagmichdoch** [comment]
Some more questions:
- is this only happening on your own instance or on pairdrop.net as well?
- Do you use any extension as in if you use an incognito tab with extensions deactivated is this still an issue?
- If you open the page in another browser (Firefox), does this issue persist? Is the icon present when you take a look via dev tools?
- If you open `/service-worker.js`, what cacheVersion does the first line say?

**Comment by schlagmichdoch** [comment]
@raceimaztion Any news?

**Comment by schlagmichdoch** [comment]
I'm closing this issue because it's stale.
