### ISSUE TITLE
"Failed to fetch" sudden connection issues

### ISSUE THREAD

**Issue by alexlyee** [schlagmichdoch/PairDrop#103]
Things have been going great for a while, but suddenly today after I used pairdrop once it began disconnecting my desktop. I got it online long enough to punch in the 6-digits to pair the two devices once but it rejected it. Here is what I'm seeing on Firefox.

![image](https://user-images.githubusercontent.com/16172638/231479161-d02a1036-a771-421b-ba7a-6191d5b68e4f.png)

The server reconnects every few seconds or so and goes through the same line of errors.

**Comment by alexlyee** [comment]
I restarted the container but it did nothing. Is there an auto-updating mechanic built-in to the container that updated it and could have caused this?

**Comment by schlagmichdoch** [comment]
There is no auto-update mechanic in place and the newest version `v1.5.3` is from two weeks ago. How do you deploy?

Your server seems to be down completely though. I cannot connect to **http://drop.within.alexs.space/**.
Are you sure you can still connect to the service? I’m not sure this is an issue with PairDrop.

**Comment by alexlyee** [comment]
@schlagmichdoch Docker compose, it's a private service, and I can connect to the website and it seems to operate fine on my phone (it loads and doesn't say it lost connection), but I haven't tested that.

Apologies for the lack of information

**Comment by schlagmichdoch** [comment]
Does it also load when you open it via a private tab? Maybe it’s just the cached version you are seeing?

**Comment by alexlyee** [comment]
You were most probably right --it was a cached version. Turned into a much larger weird problem where Windows wouldn't allow me to make outbound ICMP or HTTP requests to only my LAN (but happily did DNS and SSH). Weird, anyways, it resolved after a restart. Sorry for the bother, and thanks again for your prompt responses :)

**Comment by schlagmichdoch** [comment]
Great! Good to here it’s not a bug and the good old restart resolved it! Weird Windows problem though.
