### ISSUE TITLE
Bug/Enhancement:  iPhone issues and no luck with private IPs on 192.168.x.x

### ISSUE THREAD

**Issue by cbckly** [schlagmichdoch/PairDrop#111]
Great app, works well on pairdrop.net but not so smooth on my own docker server.

BUG: On an iPhone if I click "i" (About PairDrop) on just the plain iOS Safari browser, the "X" is not selectable.  I have to use the back button to recover.  Works fine on my PC browser.

ENHANCEMENT: I'm using the latest Docker version, but it would be nice to know the version from the web GUI to report bugs.  Could always disable displaying it if it's running from the pairdrop.net domain.

DOCKER: I'm just looking for away to transfer from my iPhone to my PC, but I can't get anything to remotely work.  The page shows up fine on my devices, I can pair them, but nothin else.  From looking at other github issues I would guess my problem is around the private ip.  Everything is running locally at 192.168.x.x.  After pairing, the gear icon lists the devices as "undefined" and never enable the center icon.  Renaming them never sticks.  I added your debug line but I'm sure it just shows what you expect.  

----DEBUGGING-PEER-IP-START----
remoteAddress: ::ffff:192.168.0.250
x-forwarded-for: undefined
cf-connecting-ip: undefined
PairDrop uses: 192.168.0.250
IP is private: true
if IP is private, '127.0.0.1' is used instead
----DEBUGGING-PEER-IP-END----
----DEBUGGING-PEER-IP-START----
remoteAddress: ::ffff:192.168.0.154
x-forwarded-for: undefined
cf-connecting-ip: undefined
PairDrop uses: 192.168.0.154
IP is private: true
if IP is private, '127.0.0.1' is used instead
----DEBUGGING-PEER-IP-END----

I'm using the linuxserver.io docker, it's not behind a proxy.  I'm just pulling up whatever webserver your or they embedded in the docker (Header's show X-Powered-By: Express).  I don't have any need to put it on a proxy and over the internet.  If I'm doing that, I might as well just use pairdrop.net.  Was hoping for quicker performance by staying on my local wifi though.  Right now, sending multiple files through pairdrop.net is very slow.    Going by your other messages, x-forwarded-for is the problem.  But not sure how to enable that locally.  

My docker was set to just the port :3333.  I tried 127.0.0.1:3333 as the docs suggested but it made no difference.

**Comment by schlagmichdoch** [comment]
> On an iPhone if I click "i" (About PairDrop) on just the plain iOS Safari browser, the "X" is not selectable. I have to use the back button to recover. Works fine on my PC browser.

Is this issue also present on pairdrop.net?
What iPhone + iOS version are you having the issue with?
I cannot reproduce this issue on either version.


> the version from the web GUI

pairdrop.net always runs the latest version. You can always find out by looking at https://pairdrop.net/service-worker.js which lists the version right at the top.
I might add the version number to the about page like so:
> PairDrop `v1.7.2`

What do you think?



> ----DEBUGGING-PEER-IP-START----
> remoteAddress: ::ffff:192.168.0.250
> x-forwarded-for: undefined
> cf-connecting-ip: undefined
> PairDrop uses: 192.168.0.250
> IP is private: true
> if IP is private, '127.0.0.1' is used instead
> ----DEBUGGING-PEER-IP-END----
> ----DEBUGGING-PEER-IP-START----
> remoteAddress: ::ffff:192.168.0.154
> x-forwarded-for: undefined
> cf-connecting-ip: undefined
> PairDrop uses: 192.168.0.154
> IP is private: true
> if IP is private, '127.0.0.1' is used instead
> ----DEBUGGING-PEER-IP-END----

Thanks for the logs!
Apparently, everything works fine serverwise and your peers are correctly detected as local and therefore presented to each other. 
It seems, that your peers cannot successfully open peer to peer webrtc connections. Everything else is a result of that.
What browsers do you use? Does PairDrop.net work with these?
Could you please provide the web console logs? It might be, that your browsers do not allow webrtc on pages over http. You could try the dev branch to create a https version via docker. Maybe this would resolve the issue. Before that browser logs would be helpful to confirm that theory though

**Comment by schlagmichdoch** [comment]
> I might add the version number to the about page

This is now done for future versions. See: https://pairdrop.net#about

**Comment by cbckly** [comment]
I just went to test my iPhone on pairdrop.net and saw the version #, so thanks for that.  Yes, I still can't click the x on the About screen.  I have a iPhone 12 Mini.  Since you mention it does work for you.  I tried it in landscape and it does work there.  Just not in portrait.  So probably something with the Minis resolution.

I'm using Brave for everything and yes, pairdrop.net worked successfully with those devices, but I was trying to avoid the internet, not for privacy reasons, but just speed.  I'm on ADSL and the upload is abysmal.  You might be onto something with the webrtc needing https.  I remember trying to quickly hack together some audio recording in the browser and it also needed to be https at which point I just gave up.

By web console log are you referring to this?  Formatting is off, but maybe it will help.  In this example, I don't have a second device, but it still shows the paired icon with the gear. 

`Database initialised.
network.js:47 WS: server connected
network.js:74 WS receive: 
Object
config
: 
{sdpSemantics: 'unified-plan', iceServers: Array(1)}
type
: 
"rtc-config"
[[Prototype]]
: 
Object
network.js:74 WS receive: 
Object
message
: 
{displayName: 'Violet Alpaca', deviceName: 'Windows Chrome', peerId: '0c62fa15-da41-4afd-873c-c65b9a3ee7ec', peerIdHash: 'ff6f8c1e0f136a97cce6c7f0db45ab8e3f7459b7ca6902da48…3f3d1389c78e05375360ebaf3a7b64e4be594107bcd7c97dd'}
type
: 
"display-name"
[[Prototype]]
: 
Object
network.js:141 successfully added peerId to localStorage
network.js:125 WS send: 
Object
type
: 
"join-ip-room"
[[Prototype]]
: 
Object
ui.js:1922 Request successful. Retrieved key-pair: editedDisplayName - ZenBrave
ui.js:57 Retrieved edited display name: ZenBrave
network.js:74 WS receive: 
Object
peers
: 
[]
roomSecret
: 
""
roomType
: 
"ip"
type
: 
"peers"
[[Prototype]]
: 
Object
2
ui.js:1982 Request successful. Retrieved 1 room_secrets
network.js:125 WS send: 
Object
roomSecrets
: 
['I5bORMx-DCPRq4pMAQ@b1AwXeo/C2ohWyaYxIsmpN8U1z5x/j5…6k1b5W2/90a7LgqvWpzt8DIux8U4i2FvUCBAVhnk@zP1bp/6U']
type
: 
"room-secrets"
[[Prototype]]
: 
Object
network.js:74 WS receive: 
Object
peers
: 
[]
roomSecret
: 
"I5bORMx-DCPRq4pMAQ@b1AwXeo/C2ohWyaYxIsmpN8U1z5x/j58MitJaCVKBruVON@rU1WghggWOtnA3/AJg4C8cW7TnSO68/3RAifpFWssEtPPQI8ncYeWzppSwnoA5FAuq4LsZb1jX5o6l0Fy5plLo@9amS49JQSErxgj0stQUwxl6NvZ6-TrXR5mngDc0NnaA8vGQ9mbDGtr6k1b5W2/90a7LgqvWpzt8DIux8U4i2FvUCBAVhnk@zP1bp/6U"
roomType
: 
"secret"
type
: 
"peers"
[[Prototype]]
: 
Object`

**Comment by schlagmichdoch** [comment]
> I just went to test my iPhone on pairdrop.net and saw the version #, so thanks for that. Yes, I still can't click the x on the About screen. I have a iPhone 12 Mini. Since you mention it does work for you. I tried it in landscape and it does work there. Just not in portrait. So probably something with the Minis resolution.

Thanks for testing again. I have just created a separate issue for that.
Let’s continue over there regarding the about close btn.

Thanks for the console log.
I will need logs while you try to connect another peer though, otherwise WebRTC is never used. A second browser tab is sufficient though, you don’t need a second device.

Do you have docker installed? I will provide a docker-compose file tomorrow, that enables you to host PairDrop via https in your own network.

**Comment by schlagmichdoch** [comment]
I'm closing this issue because it's stale. Feel free to reopen.
