### ISSUE TITLE
Bug: Android share text/file/image to PairDrop fails with 405 Not Allowed

### ISSUE THREAD

**Issue by denilsonsa** [schlagmichdoch/PairDrop#117]
**Describe the bug**
When trying to share an image (using the built-in Android share) to PairDrop PWA, it fails with HTTP error *405 Not Allowed*.

**To Reproduce**
1. Install PairDrop.net on your Android phone as a PWA through Chrome.
2. Go to any file manager app. Or to the Gallery app. Or take a screenshot and look at the notification.
3. Tap "Share". A list of available apps will show up.
4. Pick "PairDrop".

**Expected behavior**
Well, it should work. It should initiate sharing the file.

**What happens instead**
Plain nginx page with the following contents:

> **405 Not Allowed**
>
> ---
>
> nginx

**Smartphone (please complete the following information):**
 - Device: Android phone (OnePlus 3)
 - OS: Android 9
 - Browser: Google Chrome 113

**Self-Hosted**
No

**Work-around**
I can manually open the PairDrop PWA and then initiate the transfer from there. But that means I need to navigate to the file from scratch.

**Additional context**
The same broken behavior happens when sharing a piece of text (select any text, then share).

SnapDrop doesn't seem to support file sharing (through the Android Share), but it does support text sharing and it does work (although a bit clunky).

**Comment by schlagmichdoch** [comment]
Thanks for pointing it out. The http server configuration has been updated. Could you please test again?

**Comment by denilsonsa** [comment]
Thanks! Seems to be working now.
