### ISSUE TITLE
Bug: pre built Docker image -> devices not discovered

### ISSUE THREAD

**Issue by andreapx** [schlagmichdoch/PairDrop#118]
**Describe the bug**
I've switched from the docker with the script to the pre built Docker image (with Docker compose as per [the instructions](https://github.com/schlagmichdoch/PairDrop/blob/master/docs/host-your-own.md#deployment-notes)).
I'm behind Cloudflare ZeroTrust tunnel
The Pairdrop page opens, but it can't discover any device in the same network. The graphic is static, while before I remember the circle waving from the bottom center page

**To Reproduce**
1. deploy Pairdrop with docker-compose
2. open the webpage

**Expected behavior**
I expect to see the devices that has opened the Pairdrop webpage that are in the same network

**Desktop (please complete the following information):**
The container is on Ubuntu 20.04.
I've tried the client with Firefox and Chrome (all latest versions) on Windows and on Android 13

**Self-Hosted**
Yes

**Self-Hosted Setup**
Proxy: Cloudflare ZeroTrust tunnel
Deployment: docker docker-compose

**Comment by schlagmichdoch** [comment]
Do your devices connect when you pair them and it’s only the auto discovery feature that does not work properly or do paired devices not find each other as well?

To debug the auto discovery feature, please use the [debug mode](https://github.com/schlagmichdoch/PairDrop/blob/master/docs/host-your-own.md#debug-mode) to make user your setup detects the correct public ip of clients. 
When your PairDrop instance is behind Cloudflare, make sure the header `cf-connecting-ip` is set.



> The graphic is static, while before I remember the circle waving from the bottom center page

The background animation has been removed since your last deployment as it led to high cpu/gpu loads on some browsers even after it was optimized. This way, PairDrops startup time is much faster especially on less powerful devices and PairDrop is focused on its core feature.

As the animation was removed in version `v1.6.1` your last deployment must be <=`v1.6.0`. Try to deploy an older version from docker hub to ensure there were no changes to PairDrop that broke this feature for you.

**Comment by Jesse-Millwood** [comment]
I also notice this issue. 
I can initiate the pairing and see on both devices that the pairing happened successfully from the message that pops up, however I can not see any devices to share to. 
To recreate, I just used my laptop on my wifi network and my phone connected to data only. 
When both are on the same network and no pairing is required they show up just fine.

**Comment by schlagmichdoch** [comment]
> To recreate, I just used my laptop on my wifi network and my phone connected to data only.

@Jesse-Millwood This is a different issue then. If devices are not behind the same NAT they need a TURN server to connect successfully. Just deploy a turn server to make it work. See https://github.com/schlagmichdoch/PairDrop/blob/master/docs/host-your-own.md#specify-stunturn-servers

If the problem persists, feel free to open a new issue.

**Comment by andreapx** [comment]
> Do your devices connect when you pair them and it’s only the auto discovery feature that does not work properly or do paired devices not connect to each other as well?
> 
> To debug the auto discovery feature, please use the [debug mode](https://github.com/schlagmichdoch/PairDrop/blob/master/docs/host-your-own.md#debug-mode) to make sure your setup detects the correct public ip of clients. When your PairDrop instance is behind Cloudflare, make sure the header `cf-connecting-ip` is set.
> 
> > The graphic is static, while before I remember the circle waving from the bottom center page
> 
> The background animation has been removed since your last deployment as it led to high cpu/gpu loads on some browsers even after it was optimized. This way, PairDrops startup time is much faster especially on less powerful devices and PairDrop is focused on its core feature.
> 
> As the animation was removed in version `v1.6.1` your last deployment must be <=`v1.6.0`. Try to deploy an older version from docker hub to ensure there were no changes to PairDrop that broke this feature for you.

Hi Jesse,
sorry for my late reply, but I?ve totally missed the GitHub email until this new one.
I've deployed a new container right now and it works!
How about include a TURN server in your docker-compose.yaml for us lazy-ass? 😁

**Comment by schlagmichdoch** [comment]
> How about include a TURN server in your docker-compose.yaml for us lazy-ass? 😁

There is an open PR to fix the existing one: #105 #106

**Comment by andreapx** [comment]
...ops! Thanks!
I think that this _issue_ can be closed.

**Comment by schlagmichdoch** [comment]
Closing this as it resolved itself (the best kind of issue😉).

@Jesse-Millwood Feel free to open a new issue if you need help with the turn server.
