### ISSUE TITLE
Bug: iPad peer is not disappearing when safari is minimized or the screen is turned off

### ISSUE THREAD

**Issue by easez88** [schlagmichdoch/PairDrop#131]
**Describe the bug**
iPad is always available as a client even when screen is turned off. For example, when I connect from my laptop to my phone when I turn the screen off on my phone it disappears from my laptop as a sharing option (No longer connected). However, when I turn off my ipad it is still available on my laptop (Remains connected). It does not disconnect no matter how long I wait. This causes a battery drain on the ipad
**To Reproduce**
1. Go to 'https://pairdrop.net' on an ipad and another device
2. Turn off power or minimize safari without closing the pairdrop 
3. See that ipad is still available for sharing even though safari window is not open. 
4. Repeat steps 1 and 2 with another mobile device like an iphone and notice that it disappears when you turn off the screen or minimize safari. 

**Expected behavior**
The ipad to disappear when you minimize safari or turn off screen. 

**Screenshots**
![image](https://github.com/schlagmichdoch/PairDrop/assets/54665292/f2513060-81ae-435e-a8f9-41795b7a3f3f)
The only weird thing I can see is that the iPad is being recognized as a mac

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version latest

**Smartphone (please complete the following information):**
 - Device: iPad Pro 11
 - OS: iPadOS 16.5.1
 - Browser Safari
 - Version latest

**Self-Hosted**
 Yes, but happens on https://pairdrop.net as well

**Self-Hosted Setup**
Proxy: Nginx
Deployment: docker-compose

**Additional context**
n/a

**Comment by schlagmichdoch** [comment]
The only event that we can detect easily, is when the PairDrop tab is closed manually. This is working as expected.

On iOS a website is not able to detect that safari is minimized or the screen is turned off. The duration for iOS to set tabs to idle differs between devices. I guess that's the reason, why your iPhone and iPad seem to behave differently.

Apart from the technical ability, we do not want the peer to disconnect in these cases as that would mean, you would have to keep the tab in the foreground all the time until all transfers are finished.

Therefore I will close this issue.
