### ISSUE TITLE
Bug: Copy message not working correctly

### ISSUE THREAD

**Issue by whisperdancer** [schlagmichdoch/PairDrop#132]
Running self-hosted on docker via rasp pi4. Linuxserver.io image

Open in firefox on windows laptop. Right click on android phone to open message dialog. Enter a message and send.
On android phone, message comes up fine. I click copy to copy the contents of the message, but when pasting it is not the message I just sent. It's random string or some other content, but it's not the message sent. 

Sometimes when I paste the message, it's the previously sent message

**Comment by schlagmichdoch** [comment]
Please provide some more information:
- Is this reproducible on pairdrop.net?
- Are you using the latest version of PairDrop (v1.7.6 - see about page)
- What browser (incl. version number) are you using on Android?
- Which string does not work properly?

It seems as if websites on your browser are not allowed to copy strings to the clipboard. Can it simply be that "random string or some other content" is simply what had been in the clipboard before?

Please try the demo on this website on your receiving device: https://googlechrome.github.io/samples/async-clipboard/
1. Type sth into the text field
2. Tap "Copy"
3. Check in another program whether the string is successfully copied

**Comment by DucNhatNguyen** [comment]
Sorry but i really want to know how to code to scan devices in my local network. I've tried searching on the internet but it's not there or it's pretty vague.

**Comment by schlagmichdoch** [comment]
@DucNhatNguyen please do not spam issues. You might start a discussion[discussion](https://github.com/schlagmichdoch/PairDrop/discussions) or send me a private email.

**Comment by whisperdancer** [comment]
Sorry for the delayed response, was busy at a tech conference last week. Will update now:

On android, using firefox browser, 116.0 (Build # 2015964771)
The string I'm using is "The quick brown fox jumped over the lazy dog"

Tested on pairdrop.net and the copy button on the browser works fine. It doesn't work on my own self hosted instance.

Interestingly, on my phone which is a pixel 6 pro, when I copy to the clipboard a small window displays in lower left corner with the contents of what was just copied. This window pops up when using pairdrop.net and tapping Copy, but does not display when using my self hosted instance. This may be a clue.

Also, tested Please try the demo on this website on your receiving device: https://googlechrome.github.io/samples/async-clipboard/ and works successfully on the firefox android browser.

**Comment by whisperdancer** [comment]
> So the copy button works on pairdrop.net but does not work on your own instance?

Yes, correct. I am currently not using https as it's only on my LAN and felt that is overkill. However, I am running linuxserver SWAG on another Pi and could move the docker image to that server and then set it up with https. However, SWAG uses proxy config files to setup https on the service and I noticed even though they have the pairdrop image, they don't have a pairdrop proxy conf file available so I don't know how to properly setup the proxy config file. Could you assist with that and/or work with the linuxserver dev team to add a pairdrop config file? I'm happy to work with you on it and do the testing. If we can get it working, then perhaps open a PR with linuxserver to get them to add it to their proxy confs.

On another note, for maximum security I run my SWAG through cloudflare tunnel so I can set a bypass policy for my IP so that my self hosted instance will not be open and available to anyone on the internet. It's great and I highly recommend it. I've been able to host many services on home servers with no open port, cloudflare IP proxying to hide my IP and the ability to setup policies to control access on internet facing services. It integrated nicely into swag via a mod.

`https://github.com/linuxserver/reverse-proxy-confs` has no pairdrop config file

**Comment by whisperdancer** [comment]
I moved my pairdrop to another server which runs linuxserver swag as reverse proxy. Tested and copy works with https. So you are correct, https Copy button on mobile browser is blocked. Tried on 2 different browsers. Same result.

**Comment by whisperdancer** [comment]
Working great now. Thanks for creating a fantastically useful service. It's the service I didn't know I needed and now can't live without. :)

**Comment by schlagmichdoch** [comment]
Great! Thanks for the feedback! :)
Any suggestion, where we should state this to be helpful for others?

**Comment by whisperdancer** [comment]
I guess the docs would be a good place. What are your thoughts?

**Comment by schlagmichdoch** [comment]
I have simply added a note add the top of the host-your-own file: https://github.com/schlagmichdoch/PairDrop/blob/master/docs/host-your-own.md#deployment-notes

I guess this is sufficient. Thanks!
