### ISSUE TITLE
[Bug] Sending files is really slow

### ISSUE THREAD

**Issue by Joeeeeb5** [schlagmichdoch/PairDrop#141]
Basically, sending files is really slow. I have 2 devices on my 5GHz WiFi and it takes >10 minutes to send a 1gb file. Occurs when sending from Android to Windows and vice versa.

Windows 10 22H2 laptop running the latest Vivaldi and a phone on Android 12, MIUI 14 also using Vivaldi

**Comment by schlagmichdoch** [comment]
This is currently under development.

I'll close this as a duplicate of #44. Please add your information over there!
