### ISSUE TITLE
[Bug] Problem connecting to PairDrop (connecting)...

### ISSUE THREAD

**Issue by c22dev** [schlagmichdoch/PairDrop#148]
**Describe the bug**
PairDrop doesn't seem to work on my school network with error called :"WebSocket connection to 'wss://pairdrop.net/server/webrtc' failed: Error during WebSocket handshake: Unexpected response code: 302 error". network.js

**Screenshots**
<img width="1233" alt="image" src="https://github.com/schlagmichdoch/PairDrop/assets/102235607/45dd55bb-2c13-456b-923d-ca42f5b2b5e9">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser every browser
 - Version macos 13.4.1
 

**Bug occurs on official PairDrop instance https://pairdrop.net/**
Yes
Version: v1.7.7

**Bug occurs on self-hosted PairDrop instance**
Yes

**Self-Hosted Setup**
Proxy: Nginx | Apache2
Deployment: docker run | docker-compose | npm run start:prod
Version: v1.7.7

**Additional context**
Here is full JS response
`Event {isTrusted: true, type: 'error', target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}isTrusted: truebubbles: falsecancelBubble: falsecancelable: falsecomposed: falsecurrentTarget: WebSocket {url: 'wss://pairdrop.net/server/webrtc', readyState: 3, bufferedAmount: 0, onopen: ƒ, onerror: ƒ, …}defaultPrevented: falseeventPhase: 0returnValue: truesrcElement: WebSocket {url: 'wss://pairdrop.net/server/webrtc', readyState: 3, bufferedAmount: 0, onopen: ƒ, onerror: ƒ, …}target: WebSocket {url: 'wss://pairdrop.net/server/webrtc', readyState: 3, bufferedAmount: 0, onopen: ƒ, onerror: ƒ, …}timeStamp: 207759.8999999985type: "error"[[Prototype]]: Event
_onError @ network.js:207
ws.onerror @ network.js:42
error (asynchrone)
_connect @ network.js:42
(anonymes) @ network.js:188
setTimeout (asynchrone)
_onDisconnect @ network.js:188
ws.onclose @ network.js:41
`

I've also tried on my own server, hosted on replit (wich is not blocked), and it doesn't work.

**Comment by schlagmichdoch** [comment]
Probably websocket connections are completely disabled on your network. You can visit this page on multiple devices: https://websocketstest.com/
If it always says "WebSockets seem to Not Work for you :(" on the top, it is probably a network problem.

Maybe your school is using a proxy server which does not allow for websocket connections.

**Comment by c22dev** [comment]
It's written : Your browser supports WebSockets!

**Comment by schlagmichdoch** [comment]
That’s what it always initially says when opening the page with a modern browser.
If your browser and network support websockets, it must say: „WebSockets seem to Work for You!“ after a short time.

**Comment by c22dev** [comment]
yep definitely why then. any workaround ?

**Comment by schlagmichdoch** [comment]
If websockets are completely blocked by a firewall there is nothing I can do, I'm afraid.

Obviously, you could ask your school admin, whether he could tweak the firewall to allow websockets.

**Comment by c22dev** [comment]
ok, thanks.
