### ISSUE TITLE
[Enhancement] 

### ISSUE THREAD

**Issue by SteveRMann** [schlagmichdoch/PairDrop#154]
My wife has an iPhone.  How does she use PairDrop or ShareDrop without paying the $9.95 per month fee?

**Comment by schlagmichdoch** [comment]
What fee do you talk about?
There is and will never be a fee for using PairDrop. 

PairDrop is not affiliated in any way with ShareDrop although some of the underlying technology might be similar.

To use PairDrop, simply go to https://pairdrop.net/ with all your devices. They will find each other automatically if they are on the same network. If that does not work, either switch off iCloud private relay or simply pair your devices to enable them to discover each other independently of their network.

Also, this week, PairDrop will get a new feature called Temorary Public Rooms. You can then simply connect devices over the internet by joining the same room.
