### ISSUE TITLE
Is there a way to test or know if the RTC_CONFIG is valid & working?

### ISSUE THREAD

**Issue by luckman212** [schlagmichdoch/PairDrop#156]
Hi @schlagmichdoch 

Running the freshly-minted 1.8.0 in a docker container... and have my own coturn server up as well. The coturn server is passing the tests at [trickle/ice](https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/) and `stunclient stun.my-stun-server.foo 3478`

I'm wondering about my custom `RTC_CONFIG`, which I have created like so:

```
mkdir -p /root/pairdrop
cat <<EOF >/root/pairdrop/rtc_config.json
{
  "sdpSemantics": "unified-plan",
  "iceServers": [{
    "urls": "stun:stun.<my-stun-server-name-here>:3478"
  }]
}
EOF
```

and then
```
docker run -d \
--restart=unless-stopped \
--name=pairdrop \
-e TZ=America/New_York \
-e RATE_LIMIT=true \
-e WS_FALLBACK=true \
-e RTC_CONFIG="rtc_config.json" \
-e IPV6_LOCALIZE=4 \
-v /root/pairdrop/rtc_config.json:/app/pairdrop/rtc_config.json \
lscr.io/linuxserver/pairdrop:latest
```

But I'm not sure how to tell if that `RTC_CONFIG` is actually working/doing anything useful.

Is it enough to use `-e DEBUG_MODE=true` in the docker command? Any other way to test or know if I've got a working setup? Thank you 🙏

**Comment by schlagmichdoch** [comment]
You can simply open your PairDrop instance and open the browser console. One of the first entries is the following:

`WS receive: Object { type: "rtc-config", config: {…} }`

with `config` containing the content of your `rtc-config.json` if everything worked as expected.

**Comment by luckman212** [comment]
Ah, had no idea it was so simple. Ok yes, that does seem to be working fine then! Thanks again.

**Comment by schlagmichdoch** [comment]
Great! I’ll close this issue then.

Beware that you will need a TURN server instead or alongside your STUN server for internet transfers to work.

**Comment by luckman212** [comment]
I thought coturn _was_ both a STUN + TURN server... now I'm feeling confused again...

**Comment by schlagmichdoch** [comment]
True! coturn includes a TURN server if you configure it correctly.

Then you will reach the server via STUN protocol: `turn:coturn.<my-coturn-server-name-here>:3478`, via TURN protocol `turn:coturn.<my-stun-server-name-here>:3478` and optionally via TURNS protocol `turns:coturn.<my-coturn-server-name-here>:5349`. The turn server must have a username and password. To tell that PairDrop set your `rtc_config.json` to the following:

without TURN over TLS:
```json
{
  "sdpSemantics": "unified-plan",
  "iceServers": [
    {
      "urls": "stun:coturn.<my-coturn-server-name-here>:3478"
    },
    {
      "urls": "turn:coturn.<my-coturn-server-name-here>:3478",
      "username": "username",
      "credential": "password"
    }
  ]
}
```

with TURN over TLS:
```json
{
  "sdpSemantics": "unified-plan",
  "iceServers": [
    {
      "urls": "stun:coturn.<my-coturn-server-name-here>:3478"
    },
    {
      "urls": "turns:coturn.<my-coturn-server-name-here>:5349",
      "username": "username",
      "credential": "password"
    }
  ]
}
```

**Comment by luckman212** [comment]
Thanks @schlagmichdoch — I just returned from a rather steep 2-day dive into the idiosyncrasies of coturn configuration, [`turnserver.conf`](https://github.com/coturn/coturn/blob/master/examples/etc/turnserver.conf), generating TLS certs, the difference between `static-auth-secret` and `lt-cred-mech`, how to use `turnadmin` and `turnutils_uclient`, and docker volume mapping... to name a few. Not very fun!

But, I've emerged successful (I think?)

my server now passes the [Trickle/ICE](https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/) test 

![screenshot_zrRdvYlr](https://github.com/schlagmichdoch/PairDrop/assets/1992842/a0712b6a-ef94-4596-ba81-2179f1f81efe)

as well as this commandline test

```
turnutils_uclient -u my-secret-user -w hunter2 -yt -r 5349 stun.my.server.com
```

My `rtc_config.json` (using turn, _not_ turn**s** since I haven't quite figured out how to do the cert verification, and Chrome fails as a result, although Firefox happily succeeds)
```json
{
  "sdpSemantics": "unified-plan",
  "iceServers": [
    { "urls": "stun:stun.my.server.com:3478" },
    { "urls": "turn:stun.my.server.com:5349",
      "username": "my-secret-user",
      "credential": "hunter2"
    }
  ]
}
```

Thanks again for the tips.
