### ISSUE TITLE
Running PairDrop on subfolder

### ISSUE THREAD

**Issue by zap4zap** [schlagmichdoch/PairDrop#16]
Hi,

I am running PairDrop  on a subfolder instead of a subdomain using Traefik and redirect rules.
https://my.domain/pairdrop/

I got this working, by only removing the absolute path to the sound files in public/index.html
/sounds/blob.mp3 -->  sounds/blob.mp3

Possible to change this in the code?

Thanks!

**Comment by schlagmichdoch** [comment]
This is now fixed. As you asked via mail already, this is how to create a pull request: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

1. fork this repository via the button in the upper right corner
2. commit and push your changes to any of your own branches
3. create a pull request via the tab 'Pull requests' or by clicking the link that appears when pushing your changes to your fork
