### ISSUE TITLE
[Enhancement] Add Indonesian language

### ISSUE THREAD

**Issue by ianz56** [schlagmichdoch/PairDrop#161]
Please add Indonesian language, I've checked on Weblate, but it's not available for Indonesian language, so please add Indonesian language, I want to contribute in Indonesian language. Thank you

**Comment by schlagmichdoch** [comment]
Hey @ianz56,
I’ve just added Indonesian for you to translate. Thanks for contributing!

**Comment by schlagmichdoch** [comment]
Thanks a lot for your fast translation!

Is this the correct spelling of the Indonesian language in Indonesian?
![Screenshot from 2023-09-22 02-04-23](https://github.com/schlagmichdoch/PairDrop/assets/52242352/83210b51-d7a0-4585-895e-6d147ee6a1ac)

**Comment by ianz56** [comment]
Yes, that's correct ❤️
