### ISSUE TITLE
[Bug] IOS Only (Safari and Chrome): Text area not writable while sending message

### ISSUE THREAD

**Issue by FelipeGlauber** [schlagmichdoch/PairDrop#163]
Text area is not writable while sending message from iOS (Safari and Chrome tested)

Official website tested

**Comment by schlagmichdoch** [comment]
I cannot reproduce the issue. Phase provide some more info and screenshots.

**Comment by DAIL7069** [comment]
ios15 cannot edit
![065dc8d5e6bd1801147f3a91401e4ea](https://github.com/schlagmichdoch/PairDrop/assets/135861944/66f91ff0-a41b-4d84-993c-53a78bba66b0)

**Comment by schlagmichdoch** [comment]
@DAIL7069 what iPhone version is this? Do you use any extension that might interfere with the text dialog?

**Comment by DAIL7069** [comment]
> I could reproduce the error on an older iPhone but I'm not entirely sure what the problem is.
> 
> @FelipeGlauber @DAIL7069 Please verify that the bug is fixed on this instance before I merge this into master:
> 
> https://pairdrop-ios-error.onrender.com/

yeah,now I can edit.

**Comment by DAIL7069** [comment]
> Thanks for testing!
> 
> This merged and released into version 1.8.3 which is now running under https://pairdrop.net/

please check "edit name", cannot edit.
![image](https://github.com/schlagmichdoch/PairDrop/assets/135861944/0a3c3bf6-c001-4388-9272-99d60e78d6e8)

**Comment by schlagmichdoch** [comment]
What iPhone version are you using?

**Comment by DAIL7069** [comment]
> What iPhone version are you using?

iphone13 ios15

**Comment by schlagmichdoch** [comment]
Apparently, there is a specification that Apple implemented incorrectly until iOS 16.5.

@DAIL7069 please test again here, whether sending messages and editing the display name works as expected: https://pairdrop-ios-error.onrender.com

**Comment by DAIL7069** [comment]
> Apparently, there is a specification that Apple implemented incorrectly until iOS 16.5.
> 
> @DAIL7069 please test again here, whether sending messages and editing the display name works as expected: https://pairdrop-ios-error.onrender.com

its ok,work well

**Comment by schlagmichdoch** [comment]
Thanks for testing!

This is implemented into v1.9.0 which is running on https://pairdrop.net :tada:

**Comment by FelipeGlauber** [comment]
Fixed. Thanks!
