### ISSUE TITLE
[Enhancement] Add Arabic language

### ISSUE THREAD

**Issue by DGS7** [schlagmichdoch/PairDrop#167]
**What problem is solved by the new feature**
** For Arab users, language problems will be solved **

 ** Adding the Arabic language to the translation on the weblate website for a wider spread of this project **

**Comment by schlagmichdoch** [comment]
I've just added Arabic to the available languages in Weblate. If you want, you can easily help to translate PairDrop yourself over at https://hosted.weblate.org/translate/pairdrop/pairdrop-spa/ar/?q=state:%3Ctranslated

**Comment by schlagmichdoch** [comment]
As this is the first right-to-left language of PairDrop I probably need to change the localization method a bit.

Would you be open to test whether the right-to-left styling change works as expected as soon as the translation itself is finished?

**Comment by DGS7** [comment]
Yes, you are ready to try it. Just add the Arabic language to the
translation list in weblate .

في الأحد، ١ تشرين الأول ٢٠٢٣, ٧:١٧ م schlagmichdoch <
***@***.***> كتب:

**Comment by DGS7** [comment]
Great thanks ! .

في الأحد، ١ تشرين الأول ٢٠٢٣, ٧:١٢ م schlagmichdoch <
***@***.***> كتب:

**Comment by DGS7** [comment]
Finally, I have just finished translating the entire website into Arabic .

في الأحد، ١ تشرين الأول ٢٠٢٣, ٧:١٢ م schlagmichdoch <
***@***.***> كتب:

**Comment by schlagmichdoch** [comment]
Thank you! I will let you know as soon as the test instance is up and running.

**Comment by DGS7** [comment]
Ok, thanks.

في الأربعاء، ٤ تشرين الأول ٢٠٢٣, ١٢:٢٢ ص schlagmichdoch <
***@***.***> كتب:

**Comment by schlagmichdoch** [comment]
I implemented support for RTL languages.

 Please test thoroughly whether everything looks and works as expected on Arabic websites on this instance: https://pairdrop-dev.onrender.com/

**Comment by DGS7** [comment]
No, there is nothing duplicated.

في الخميس، ٥ تشرين الأول ٢٠٢٣, ٥:١٣ م schlagmichdoch <
***@***.***> كتب:

**Comment by schlagmichdoch** [comment]
This is implemented into v1.9.0 which is running on https://pairdrop.net

I will leave this open though as I'm still not sure about my last post.

**Comment by DGS7** [comment]
Ok, thanks for the update.

في الخميس، 12 تشرين الأول 2023, 3:03 م schlagmichdoch <
***@***.***> كتب:
