### ISSUE TITLE
[Enhancement] Add Spanish Language

### ISSUE THREAD

**Issue by elBelgg** [schlagmichdoch/PairDrop#169]
**What problem is solved by the new feature**
Spanish people will have the website in their own language

**Describe the feature**
Add Spanish language. I would like to help the project translating it

**Comment by schlagmichdoch** [comment]
I have just added Spanish to the available languages in PairDrop's Weblate:
https://hosted.weblate.org/projects/pairdrop/pairdrop-spa/es/

I will close this issue as soon as you have translated all the strings and Spanish is added to pairdrop.net.

**Comment by elBelgg** [comment]
Done.

------- Original Message -------

**Comment by elBelgg** [comment]
Done.

**Comment by schlagmichdoch** [comment]
Are you sure you have saved your changes? Weblate is still empty for me: https://hosted.weblate.org/projects/pairdrop/pairdrop-spa/

**Comment by elBelgg** [comment]
I marked them as suggests

**Comment by schlagmichdoch** [comment]
This is implemented into v1.9.0 which is running on https://pairdrop.net :tada:
