### ISSUE TITLE
[Enhancement]  Add Dutch language

### ISSUE THREAD

**Issue by penguix0** [schlagmichdoch/PairDrop#171]
**What problem is solved by the new feature**
I want Dutch people to be able to use this app in their native language.

**Describe the feature**
Add the Dutch language to weblate for PairDrop, I will translate it.

**Comment by schlagmichdoch** [comment]
I have just added Dutch to the available languages in PairDrop's Weblate:
https://hosted.weblate.org/projects/pairdrop/pairdrop-spa/nl/

I will close this issue as soon as you have translated all the strings and Dutch is added to pairdrop.net.

**Comment by penguix0** [comment]
Most of the English strings use multiple capital words in one sentence. Should I do it in this way in Dutch too, the German translation does this sometimes, not always.

**Comment by penguix0** [comment]
I finished translating all the strings.

**Comment by schlagmichdoch** [comment]
> Edit: English is also inconsistent with the use of capital words midsentence

I tried to capitalize all English titles via https://capitalizemytitle.com/ which leads to capitalized words mid sentence.

These are e.g. the hover titles of buttons and - more importantly - headers of all dialogs like this:
<img src="https://github.com/schlagmichdoch/PairDrop/assets/52242352/a89a9a88-9c31-4c40-967b-1a8a7af4698d" width="200px"/>

I guess you should find all titles that should be capitalized here:
https://hosted.weblate.org/zen/pairdrop/pairdrop-spa/nl/?q=title+AND+NOT+document-titles+AND+NOT+dialogs.title-+AND+NOT++notifications.request-title&sort_by=-priority%2Cposition&checksum=

**Comment by penguix0** [comment]
Ah okay, that makes sense. I corrected all dialog headers and checked all other strings to make sure they are capitalized correctly.

**Comment by schlagmichdoch** [comment]
This is implemented into v1.9.0 which is running on https://pairdrop.net :tada:
