### ISSUE TITLE
[Enhancement] Add Italian language

### ISSUE THREAD

**Issue by awashingmachine** [schlagmichdoch/PairDrop#172]
I can translate to Italian

**Comment by schlagmichdoch** [comment]
Thanks for your offer to contribute!

I have just added Italian to the available languages in PairDrop's Weblate:
https://hosted.weblate.org/projects/pairdrop/pairdrop-spa/it/

I will close this issue as soon as you have translated all the strings and Italian is added to pairdrop.net.

**Comment by awashingmachine** [comment]
Done :)

**Comment by guba91** [comment]
> I can translate to Italian

Mi hai anticipato di un giorno LOL

**Comment by schlagmichdoch** [comment]
> Mi hai anticipato di un giorno LOL

@guba91, I still need a day or two to merge everything into a new version. In the meantime, you can check if you’re fine with the translation of @awashingmachine

**Comment by schlagmichdoch** [comment]
This is implemented into v1.9.0 which is running on https://pairdrop.net :tada:
