### ISSUE TITLE
[Enhancement] Add a copy link button on pairing and room menus

### ISSUE THREAD

**Issue by awashingmachine** [schlagmichdoch/PairDrop#174]
I think that adding a copy link button or just displaying a link to a device or to a room is much faster if for example you want to share files between two PCs not on the same network. I think that it saves you a few clicks and is much more straightforward if you have to send a file to someone that never used PairDrop

**Comment by schlagmichdoch** [comment]
This has been discussed a lot already over at Snapdrop before PairDrop was created. The consensus was, that if users already have a way to send each other a link, they probably don’t need to use PairDrop at all. This is why I decided for the 6-digits code for pairing and 5-letter code for public rooms. The QR code makes sense for people meeting in person.

Could you describe the scenario you might use the feature in?
You’re connected to someone on Discord and want to send them a file via PairDrop. You want them to click on a link to be connected to you on PairDrop immediately?

I guess the url you’re looking for already exists (`https://pairdrop.net/?room_key=CIAAA`) and is encoded via the QR-code. Beware though, that the url only works if the room already exists so you cannot create a new room with a preferred ID this way.
(Also I will change the url argument to `room_id` to be consistent in a future version)

I do not want to bloat the pairing and public room dialogs any further as these are quite complicated already. Maybe we could do sth like *click the QR code to copy the share url*. What do you think?

**Comment by awashingmachine** [comment]
Sometimes I have to work with people over 40 that are very stubborn to change. Having them just click on a link and accept receiving a file is much faster than telling them to click on the chain icon and then insert my code ecc. 
I think that the "click the qr code to copy the link" feature is a clean and wonderful solution.

**Comment by schlagmichdoch** [comment]
@awashingmachine I'd appreciate it if you could quickly test whether everything works as expected:
https://pairdrop-dev.onrender.com/

I have added a note to the QR-code title which should be visible on mouse hover.

**Comment by awashingmachine** [comment]
Copy link by clicking on qr code works as intended, tested both on desktop and mobile. Good job 👍

**Comment by schlagmichdoch** [comment]
Thanks for testing!

This is implemented into v1.9.0 which is running on https://pairdrop.net :tada:
