### ISSUE TITLE
[Enhancement] Add Japanese language

### ISSUE THREAD

**Issue by Rintan** [schlagmichdoch/PairDrop#175]
**What problem is solved by the new feature**
Japanese people will be able to use this in the native language.

**Describe the feature**
Please add Japanese to the Weblate project. I will contribute to it.

**Comment by schlagmichdoch** [comment]
Thanks for your offer to contribute!

I have just added Japanese to the available languages in PairDrop's Weblate:
https://hosted.weblate.org/projects/pairdrop/pairdrop-spa/ja/

I will close this issue as soon as you have translated all the strings and Japanese is added to pairdrop.net.

**Comment by Rintan** [comment]
I've finished!

**Comment by schlagmichdoch** [comment]
This is implemented into v1.9.0 which is running on https://pairdrop.net :tada:
