### ISSUE TITLE
[Enhancement] add a chat room

### ISSUE THREAD

**Issue by DAIL7069** [schlagmichdoch/PairDrop#178]
Sometimes I want to record some text or files and sync them across multiple platforms. All I want is a chat room where I can send texts and files and the recordings will be saved for viewing and copying at any time.

**Comment by schlagmichdoch** [comment]
I think this is out of this scope of this project. PairDrop is about synchronous communication only, so there will never be any feature with the need to save anything on the server.

I guess what's closest to a chat room is the following project, although this is for messages only: https://drop.lol

**Comment by schlagmichdoch** [comment]
I propose you simply use Signal which includes a chat called "Note to Self" which will then be encrypted to yourself and sent to all your devices. Closing this as out of scope.
