### ISSUE TITLE
Devices do not appear at all while they did on snapdrop through VPN

### ISSUE THREAD

**Issue by alexlyee** [schlagmichdoch/PairDrop#18]
I've two devices that are on a 10.0.0.0/24 subnet created by wireguard on pfsense. My main LAN net is not this. I can connect to the web-service and pair them, but unlike snapdrop (where I couldn't send anything), I can't even see the other device. Does this have to do with a firewall setting on nginx?

The behavior is exactly the same when I connect via. my reverse proxy, or directly via HTTPS and HTTP. I've tried combinations of Firefox and Edge on Windows 10 with Firefox and Safari on iOS 16.0.2

**Comment by schlagmichdoch** [comment]
This has to do with VPN itself. I'm not sure about wireguard on pfsense but some VPN clients simply decline all WebRTC requests, to prevent an IP leak to the connecting device. WebRTC is the technology PairDrops peer two peer connection relies on and is essential for it to work.
To check if WebRTC works on your device you can visit https://www.webrtc-experiment.com/DetectRTC/#isWebRTCSupported
If it says Browser Supports WebRTC: Nope, PairDrop will most likely not work. To read more about WebRTC leakage see [here](https://privacysavvy.com/security/safe-browsing/disable-webrtc-chrome-firefox-safari-opera-edge/).
Many VPN hosters offer the possibilty to route webrtc request through a proxy, which again hides your IP address and makes the technology available behind a VPN.

Do you get any error messages in the javascript console on the vpn devices? My best guess is that you have to specifically enable WebRTC or use another client/browser

Snapdrop shows devices immediately eventhough the connection is not (yet) established. Therefore, you see devices and can interact with them but the actual transfer does not work. PairDrop only shows devices when a successfull peer to peer connection is established. This way, when a device is shown, the transfer of messages and files will always work.

**Comment by schlagmichdoch** [comment]
@alexlyee Do you host PairDrop yourself or do you use pairdrop.net?
There used to be a fallback for situations where WebRTC is not available that uses Websockets instead of WebRTC but it has never been implemented completely. All traffic send between devices using this fallback is not peer to peer and routed through the server. 

There are two reasons why I won't implement this on the public PairDrop:
- The traffic would be readable by the server when it is routed to the recipient peer. No end-to-end encryption would prevent that you would need to trust the server. In contrast, the current implementation does not even need the server. If you host PairDrop yourself you can even switch off the server after discovery as everything works peer to peer.
- If the traffic is routed through the server, every file transfer would debit the servers data plan. Currently, only ~100KB is transferred on first visit and some KBs are used for signaling between devices.

I could only imagine implementing this on a seperate branch for users who want to self-host a private instance that they can trust completely.

**Comment by alexlyee** [comment]
@schlagmichdoch You are absolutely correct I'm certain that it is the case that my VPN is blocking WebRTC. Thanks for your prompt and complete response!

I self-host. I --for one-- would be a huge fan if there could be an option to allow pairdrop to act as a relay server if WebRTC failed.

**Comment by schlagmichdoch** [comment]
@alexlyee 
I had some time on my hands and gave it a try . There is now a second branch specificially for this feature: https://github.com/schlagmichdoch/PairDrop/tree/implement_ws_peer_for_self_hosting 🚀 

You can also test it here: https://pairdrop-dev.onrender.com/ Be aware that the transfer speed for this fallback is dependend on the speed of the relay server which is quite slow for this demo as it is a free instance.

Would be great if you could try to use this on your own instance and with your VPN clients and give some feedback before I add this new possibility to the FAQ :)

**Comment by alexlyee** [comment]
@schlagmichdoch great! I gave it a try and I'm experiencing the same trouble w/ the same two devices on a 10.0.0.0/24 subnet. It's worth mentioning that my server on my LAN at home is **not** a standard RFC 1918 private subnet. I noticed in the code while brushing over it that there is a function to test if the connecting address is an expected private IP range? This may be what is causing problems for me. What do you think is the best solution for someone like me?

**Comment by schlagmichdoch** [comment]
Are the devices in your subnet connected to the internet? There is now the edge case that a device can use webRTC but cannot connect to the public stun servers. What does the JavaScript console say? Can you provide some logs? A solution would be to host your own stun server via coturn. This could also be added to the docker-compose file.

Subnet 10.0.0.0 means ip addresses range from 10.0.0.0 to 10.255.255.255, isn’t it? This is part of the ipIsPrivate function and should map your devices together in one room. What does the „/24“ at the end mean?

This is probably no problem with the IP addresses as you would be able to bypass that by pairing the devices.

**Comment by alexlyee** [comment]
@schlagmichdoch My bad, I forgot to mention that I was testing only the branch that you linked. The testing site you linked works flawlessly! Any chance we could push this to main and allow the relay server to be enabled via. an envar?

**Comment by schlagmichdoch** [comment]
> Also, 10.0.0.X/24 means 10.0.0.0 - 10.0.0.255. You can read more about CIDR notation [here](https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing).

Thanks, good to know!

> Any chance we could push this to main and allow the relay server to be enabled via. an envar?

Not quite sure yet how the code would be structured ideally. I don't want to ship script files that includes the relay fallback to a client on an instance where the relay is not activated. I'll look into it!

**Comment by schlagmichdoch** [comment]
> Any chance we could push this to main and allow the relay server to be enabled via. an envar?

I decided to put everything in a seperate public folder to keep everything tidied up.

You can now use this by using `npm start -- --include-ws-fallback` or `npm run start:prod -- --include-ws-fallback` to run PairDrop. For further information see [here](https://github.com/schlagmichdoch/PairDrop/blob/master/docs/host-your-own.md#websocket-fallback-for-vpn). 🎉

**Comment by alexlyee** [comment]
@schlagmichdoch Fantastic!! I typically start pairdrop using docker compose. How would you go about making this happen in there? The beginning of my compose file looks like this, but it seems to be acting no different, and the logs aren't either.

```yml
version: "3"
services:
  node:
    image: "node:lts-alpine"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: ash -c "npm i && npm start -- --include-ws-fallback"
    restart: unless-stopped
```

**Comment by schlagmichdoch** [comment]
This should now work:

The docker-compose.yml was not yet intended or optimized for use on production. Someone else suggested to move everything needed only for developing to another branch so I did that and made the docker-compose.yml production-ready.

As nginx is now completely removed, you can now start PairDrop via the docker-compose file as you tried before. I would suggest replacing `npm run start:prod` with `npm run start:prod -- --include-ws-fallback` though. See [host-your-own.md](https://github.com/schlagmichdoch/PairDrop/blob/master/docs/host-your-own.md) for more information.

**Comment by schlagmichdoch** [comment]
@alexlyee  Can I close this issue now?

**Comment by alexlyee** [comment]
@schlagmichdoch Yep! Works like a charm. Great job and thank you very much :))
