### ISSUE TITLE
[Bug] Superior icons disappear and can't link my phone again to a computer in a different network 

### ISSUE THREAD

**Issue by Manrochri** [schlagmichdoch/PairDrop#182]
**Describe the bug**
I linked my phone to a computer. Both of them in a different network. However, when I unlinked my phone from previous devices, the icons that allow me to link my phone to other devices disappear 

**To Reproduce**
1. Go to the link icon
2. Link the phone to a device from a different network 
3. Unlink the phone
4. The icons to link the phone to other devices disappear. 

**Expected behavior**
The button to link the devices to other devices from different networks disappear 

**Screenshots**
![Screenshot_20231019-090528](https://github.com/schlagmichdoch/PairDrop/assets/119143925/02c9bb5b-2091-406c-8ef8-007b8539bc52)

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Browser : Google Chrome 
 - Version that 118.0.5993.88

**Smartphone (please complete the following information):**
 - Device: Huawei y7 2019
 - OS: Android 8
 - Browser Pairdrop App

**Bug occurs on official PairDrop instance https://pairdrop.net/**
Yes
Version: v1.9.1

**Comment by schlagmichdoch** [comment]
This is not an issue of PairDrop but rather of the app you are using: https://github.com/fm-sys/snapdrop-android

Please create an issue over there. I could provide an PR if @fm-sys is busy right now.

**Comment by fm-sys** [comment]
Yes, quite busy currently. PRs are more than welcome!

**Comment by schlagmichdoch** [comment]
@Manrochri This should be fixed now. Please try again!

**Comment by Manrochri** [comment]
It is fixed. Thank you so much
________________________________
De: schlagmichdoch ***@***.***>
Enviado: viernes, 20 de octubre de 2023 10:50
Para: schlagmichdoch/PairDrop ***@***.***>
Cc: CHRISTIAN MANUEL RODRIGUEZ CHILET ***@***.***>; Mention ***@***.***>
Asunto: Re: [schlagmichdoch/PairDrop] [Bug] Superior icons disappear and can't link my phone again to a computer in a different network (Issue #182)


@Manrochri<https://github.com/Manrochri> This should be fixed now. Please try again!
