### ISSUE TITLE
[Bug] Can't scan QR Code in dark mode

### ISSUE THREAD

**Issue by Mitia99** [schlagmichdoch/PairDrop#187]
**Describe the bug**
Can't scan QR Code in dark mode

**To Reproduce**
1. Set theme to Dark
2. Pair devices with QR Code

**Expected behavior**
Pair devices

**Screenshots**
Can't pair due to inverted QR color
![Screenshot 2023-10-23 101619](https://github.com/schlagmichdoch/PairDrop/assets/56766778/c3b4a925-b5cc-4009-9a07-3e3bff7cf477)

**Solution**
Don't modify QR Code in dark mode
![Solution](https://github.com/schlagmichdoch/PairDrop/assets/56766778/24b2b318-6459-45f0-8435-b198995ce5e5)

**Comment by schlagmichdoch** [comment]
With which device did you try to scan the QR-Code?

**Comment by Mitia99** [comment]
> With which device did you try to scan the QR-Code?

My phone (Huawei P30) with different 3rd party QR Scanner apps. Can you scan the first screenshot I provided? I edited the second one.

**Comment by Mitia99** [comment]
I tried with [QR & Barcode Scanner](https://play.google.com/store/apps/details?id=com.trustedapp.qrcodebarcode) and it was able to open the link.

Anyway, not inverting the QR will be better for new users who will struggle to find an app which supports inverted QR

**Comment by schlagmichdoch** [comment]
On iOS the camera app can scan QR-Codes with inverted colors natively.
I want devices to be able to do this via their native camera apps as well.

 As I think this the QR-code standard also dictates black icons on light background, I second the idea of removing the inversion of colors for QR-codes.

With your preferred QR-code scanners, can you scan the code like this?

<image src="https://github.com/schlagmichdoch/PairDrop/assets/52242352/348edc79-7f6f-4db3-8b9f-14770719e558" width="400px">

**Comment by Mitia99** [comment]
> On iOS the camera app can scan QR-Codes with inverted colors natively.
> I want devices to be able to do this via their native camera apps as well.
> 
>  As I think this the QR-code standard also dictates black icons on light background, I second the idea of removing the inversion of colors for QR-codes.
> 
> With your preferred QR-code scanners, can you scan the code like this?
> 
> <image src="https://github.com/schlagmichdoch/PairDrop/assets/52242352/348edc79-7f6f-4db3-8b9f-14770719e558" width="400px">
> 

Yes, I can scan the QR you provide.
Thank you,

**Comment by schlagmichdoch** [comment]
Fixed in `v1.9.4` and running live on the official instance https://pairdrop.net/
