### ISSUE TITLE
[Enhancement] Built-in QR Code scanner

### ISSUE THREAD

**Issue by Mitia99** [schlagmichdoch/PairDrop#188]
**What problem is solved by the new feature**
Scanning QR will be more convenient

**Describe the feature**
A built-in QR Code Scanner

**Additional context**
Other sharing solution like [Xender](https://play.google.com/store/apps/details?id=cn.xender&hl=fr&gl=US) have a built-in QR Code Scanner which is convenient.

Ty for considering this,

**Comment by schlagmichdoch** [comment]
I'm not sure about this as this would clutter the pairing and public room dialogs even more. I mean its only 6 digits or 5 letters so it's pretty straight forward as is, don't you think?

**Comment by Mitia99** [comment]
Indeed, the digits/letters is straight forward.
I was just thinking that as the instance supports QR it will be convenient to directly have a scanner in the Android app like Xender.

**Comment by Mitia99** [comment]
@schlagmichdoch Do you maintain the Android ? I mean this request is for the Android app and not `pairdrop.net`

**Comment by Mitia99** [comment]
> This repo is for the underlying PairDrop which is running on pairdrop.net.
> 
> I do not maintain the Android app.
> 
> QR code reader could be implemented on both levels but I guess it makes more sense in the Android app. Maybe a shortcut to open the scanner would make sense as well.

I see. I created a request in Snapdrop-android repo and I'll close this one then.

**Comment by Mitia99** [comment]
@schlagmichdoch As a contributor, any help(PR) from you in the snapdrop-android repo for that feature will be appreciated. Ty
