### ISSUE TITLE
[Bug] Can't execute Batch files with PairDrop PWA installed

### ISSUE THREAD

**Issue by RuiNtD** [schlagmichdoch/PairDrop#190]
**Describe the bug**
While PairDrop is installed as a PWA on Windows, I can't open batch files from File Explorer. I'm only presented with the option to open the file in PairDrop.

**To Reproduce**
1. Install PairDrop as a PWA.
2. Create or [download](https://gist.github.com/RuiNtD/abeea944dacc5e55ca1eafdc287db138) a batch (.bat) file.

**Expected behavior**
The bat file opens in Command Prompt and executes.

**Screenshots**
![image](https://github.com/schlagmichdoch/PairDrop/assets/1149870/3ee9dd8c-cee1-4369-97b3-e9049ae05ed4)

**Desktop:**
 - OS: Windows 11
 - Browser: Microsoft Edge
 - Version: 118.0.2088.69

**Bug occurs on official PairDrop instance https://pairdrop.net/**
Yes
Version: v1.9.4

**Additional context**

**Comment by schlagmichdoch** [comment]
I implemented the [File Handling API](https://learn.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/handle-files) to send files via the Windows Context menu.

I was aware that you had to reset the default program for file extensions. I wasn’t aware that you cannot specify to use the default application again on Windows. Normally, `C:\Windows\system32\cmd.exe` is used to execute batch files but when that is selected via the `open with` dialog it simply throws an error.

I’ll try to find a better way to send files via the context menu on Windows. Until then I would suggest to install the PWA via Firefox,  or use Chrome and go to the Chrome app settings and disable the file extension registration.

Sorry for the inconvenience!

**Comment by Mitia99** [comment]
> I implemented the [File Handling API](https://learn.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/handle-files) to send files via the Windows Context menu.
> 
> I was aware that you had to reset the default program for file extensions. I wasn’t aware that you cannot specify to use the default application again on Windows. Normally, `C:\Windows\system32\cmd.exe` is used to execute batch files but when that is selected via the `open with` dialog it simply throws an error.
> 
> I’ll try to find a better way to send files via the context menu on Windows. Until then I would suggest to install the PWA via Firefox,  or use Chrome and go to the Chrome app settings and disable the file extension registration.
> 
> Sorry for the inconvenience!

This bat file association with Edge PWA was very frustrating. I even went into some [registry tweaks](https://www.winhelponline.com/blog/bat-files-do-not-run-when-double-clicked-fix-association/?expand_article=1) which I didn't want to do due to potential OS crash. It didn't fixed the bug and I only figured it out later that it was due to Pairdrop PWA Edge app so I ended up uninstallling the PWA app.

Ty for fixing this,
