### ISSUE TITLE
Bug in UI when 2 device send files to another simultaneously

### ISSUE THREAD

**Issue by hoangnhatng** [schlagmichdoch/PairDrop#20]
"For example: A and B send requests to C simultaneously (both file and message requests). On C side, only one dialog box is displayed because the dialog box is too big and covers the middle of the screen, causing one request from the requesting device to be missed."

**Comment by schlagmichdoch** [comment]
What devices are you using? Could you provide some screenshots? What is the current behavior and how would you expect it to be?

**Comment by hoangnhatng** [comment]
A send a Dog picture to C
![A](https://user-images.githubusercontent.com/52059490/217504260-f43f035c-f6b3-4ea4-96f9-abb5e515daef.PNG)

B send a Cat picture to C
![B1](https://user-images.githubusercontent.com/52059490/217504485-ff8e00c2-ee22-4b38-b8b2-32513cdec584.png)

In C just show dialog box to accept request from B, after accept it just download a Cat picture ( lost Dog picture send from A)
![C1](https://user-images.githubusercontent.com/52059490/217504584-b58d446e-cb6b-4a01-91e1-b4c6cc510c7d.PNG)
![C2](https://user-images.githubusercontent.com/52059490/217505791-ea956326-7478-406f-8674-1e19e1f67c19.PNG)

The solution maybe like sharedrop.io UI , they don't show review image and show dialog at avatar of the device. 

![solution](https://user-images.githubusercontent.com/52059490/217505825-a88a3ae1-f1aa-4dbc-9e53-2566d777e98e.PNG)

**Comment by hoangnhatng** [comment]
It's work great. I think you need same fixing with "message request".

**Comment by schlagmichdoch** [comment]
Well I should have thought about that 🙄 Fixed by https://github.com/schlagmichdoch/PairDrop/commit/b0e798b3cd35ca69cdf1b8f157908fec223fc412. Could you test again?

**Comment by hoangnhatng** [comment]
It's worl well. Thanks for your help
