### ISSUE TITLE
[Enhancement] Adding Catalan language

### ISSUE THREAD

**Issue by gmassipg** [schlagmichdoch/PairDrop#217]
I know that it isn't a language spoken by too many people around the globe, but I'd be glad to translate the project if it were to be added to the Weblate translation page. I'm just looking to contribute for a bit wider spread of the project.

**Comment by schlagmichdoch** [comment]
I'm happy to add Catalan to PairDrop. I've just added it to the hosted Weblate: https://hosted.weblate.org/projects/pairdrop/pairdrop-spa/ca/

Ping me here when you have finished translating.

**Comment by gmassipg** [comment]
Thanks! I'm already done with the translation.

**Comment by schlagmichdoch** [comment]
This is included in the freshly released version `v1.10.1`. Thanks for contributing! :)
