### ISSUE TITLE
[Feature Request] All-in-one docker 

### ISSUE THREAD

**Issue by zhdenny** [schlagmichdoch/PairDrop#22]
Any chance of creating an all-in-one docker container for this for ease of Self-Hosted deployment? I know Unraid users would appreciate it

**Comment by schlagmichdoch** [comment]
How’s that different to the provided Dockerfile and docker-compose.yml? Could you give me an example?

**Comment by zhdenny** [comment]
An example would be something like Sonarr or Radarr. Everything is rolled into a single container.

Your compose consists of two containers.

There's nothing actually wrong, it's just more complicated for some users to setup is all.

Similar to when Bitwarden official had a four container docker setup... Then VaultWarden came around and released a simpler all-in-one container deployment (among other things)

**Comment by rursache** [comment]
Also setup github actions to build the docker container so we don't have to git clone and build the container constantly.

**Comment by schlagmichdoch** [comment]
@zhdenny 
On production, the nginx container can be completely removed when the node container exposes port 3000 instead (see [host-your-own.md](https://github.com/schlagmichdoch/PairDrop/blob/master/docs/host-your-own.md))
```yml
    ports:
      - "3000:3000"
```

Including nginx with openssl into the docker-compose is useful for development though. How would you suggest to structure the files? Should I create a second docker-compose.yml with one for development and one for production? Or rather put the development stuff in a subfolder and put the production ready compose file in the root directory instead?

**Comment by zhdenny** [comment]
Maybe create a development branch and a production/master branch in GitHub. I see a lot of devs do that.

**Comment by Leolele99** [comment]
For a good reference on what I and others here would probably like for a full production ready docker setup, look back at snapdrop.
There is the official way of installing it, which is basically the same as yours, and then there is the 3rd party linuxserver version on dockerhub https://hub.docker.com/r/linuxserver/snapdrop which allows for rootless operation and requires no additional building or pulling to update.

Not that its super neccessary, but it would fit the spirit of this project I'd say :D

**Comment by schlagmichdoch** [comment]
> Also setup github actions to build the docker container so we don't have to git clone and build the container constantly.

Should now be set up.

> Maybe create a development branch and a production/master branch in GitHub. I see a lot of devs do that.

I just moved everything needed only for development to a separate branch and tidied up the Dockerfile, docker-compose.yml and the documentation.

Is this sufficient for now? @zhdenny @rursache 

@Leolele99 Sounds great! Can I create such a linuxserver version myself or how would I have to proceed? Does the image then update automatically when there are changes to this repository?

**Comment by Leolele99** [comment]
@schlagmichdoch 
Linuxserver is just a group that takes software without single official docker images and makes them available as such. They are trusted and well maintained and have automatic pull and build processes so you are guaranteed a swift update if the original project has one.
Since they already created an image for snapdrop, you could have success just reaching out to them and asking them if they could create one for you.

There are however some caveats to this:
- It's ultimately their image and out of your hands. That can be a positive thing, but if you like to work hands on it might also be a negative.
- While they add some basic environment variables on the get go (usually just timezone and GID/UID for rootless operation (which are super important for production setups)), you might want to add further customization options to your image and project in the future. Since PairDrop has no need for a full admin interface and user managment, the best way to do this in docker would be with Environment variables, which you can only fully control if you create your own official docker image.

Full disclosure, I have not yet built my own full image, but it seems to be easy enough.
Here is the offical documentation on how to start: https://docs.docker.com/build/building/packaging/
But there are plenty more guides out there that go into full depth :)

Thanks for putting in the work!

**Comment by ovizii** [comment]
I totally agree and [Leolele99](https://github.com/Leolele99) has pretty much summed it up. Except, there's not only linuxserver there's also https://hotio.dev/ as an alternative group. 

But you can do your own thing except please don't force us to use git to download extra resources. 

Btw. I've seen much worse solutions where you not only have to clone a repo but then have to run some bash scripts which eventually launch your container(s). 

In my opinion involving git clone (and scripts) is pretty much against the general benefits of containers "Fast deployment, ease of creating new instances, and faster migrations. Ease of moving and maintaining your applications."

**Comment by schlagmichdoch** [comment]
Thanks @Leolele99 and @ovizii !
I'll look into it and come back if there are any updates

**Comment by schlagmichdoch** [comment]
> As for unraid specific, you can read more about here if you want. This way you can provide CA Template for your own.
> 
> https://forums.unraid.net/topic/57181-docker-faq/#comment-566084

@fabricionaweb Do I need to own an unraid licence to be able to publish an image?

**Comment by schlagmichdoch** [comment]
Thanks that helps! Indeed kind of a lock-in mechanism by Unraid :/

> As for creating the XML file, an Unraid user like us can help get you that

Would be great if you could create that xml with the information found in the docs for me.

Alternatively, you can open the form including the advanced section and post a screenshot here for me to fill out:
> 3. Fill out all of the relevant information, including the advanced section.  Note that you DO NOT need to fill out  host volumes.  It is OK however to fill out the host ports.  I would however recommend against filling out any host paths.

I will then publish the xml file here: https://github.com/schlagmichdoch/unraid-templates and PM squid.

**Comment by zhdenny** [comment]
So docker users typically look for the docker image to be already published and available. Docker users don't build the image themselves. Devs use a docker building repo like Github/Dockerhub to do this for them. Once done, it can be referenced in the Unraid XML file. This isn't something just for Unraid either....this is pretty much for all docker users.

Glad to hear LinuxServer is open to helping you. They can be rather strict.....so keep an open mind with them. But having your image on LinuxServer is a big step and will highly increase your project's exposure. So be prepared.

Here is some info to help you get the image built via Github
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

**Comment by schlagmichdoch** [comment]
The image is now live under `lscr.io/linuxserver/pairdrop` 🎉 

See the updated documentation to find out more:
https://github.com/schlagmichdoch/PairDrop/blob/master/docs/host-your-own.md#deployment-notes
