### ISSUE TITLE
Favicon changed? now showing up white on white

### ISSUE THREAD

**Issue by luckman212** [schlagmichdoch/PairDrop#235]
Not sure if this started in 1.10.3 but my favicon is now almost invisible :(

#### normal

<img width="368" src="https://github.com/schlagmichdoch/PairDrop/assets/1992842/cdec4cd8-6e5f-4bf3-a46f-3c2d77ab5a7a">

#### hover

<img width="49" alt="image" src="https://github.com/schlagmichdoch/PairDrop/assets/1992842/b48b191c-5e58-4884-b9c0-85b92223023a">

**Comment by luckman212** [comment]
Not sure if it's related to this error in my console

![image](https://github.com/schlagmichdoch/PairDrop/assets/1992842/1fce0ad4-10ef-4ea4-b816-32911f8977b6)

found this: https://github.com/iamshaunjp/pwa-tutorial/issues/1

**Comment by schlagmichdoch** [comment]
Not related to the error.

I've changed all icons to be consistent on all platforms:
https://github.com/schlagmichdoch/PairDrop/blob/master/public/images/android-chrome-512x512.png

I really like the clean look of the simple white favicon as GitHub does it:
Firefox dark mode:
![image](https://github.com/schlagmichdoch/PairDrop/assets/52242352/cba43814-976e-41bb-996f-b3d7e5381848

Apparently, I have missed though, that some people are still using light mode on some browsers with light navbars :see_no_evil:

Sorry for the inconvenience!

We have two possibilities now: 
1. Two favicons: One for light mode, one for dark mode
2. One favicon that has high contrast on all backgrounds

## Two favicons
This is done by GitHub: Normally the favicon is black. The page then detects whether the browser prefers dark mode and uses a white favicon instead. You can check this by opening github.com and changing the browser settings.
This seems to work on Firefox (and probably Safari) but does not show the correct icon on Chromium and also if the header bar is always dark.

Firefox dark mode:
![image](https://github.com/schlagmichdoch/PairDrop/assets/52242352/cba43814-976e-41bb-996f-b3d7e5381848)

Firefox light mode:
![image](https://github.com/schlagmichdoch/PairDrop/assets/52242352/4921b7af-77ed-4fe2-98f4-922441031289)

## One favicon with high contrast
I'd prefer this. I would then use the white icon on blue background that is already used for everything else:
Chromium light mode:
![image](https://github.com/schlagmichdoch/PairDrop/assets/52242352/834a0455-0773-41a8-b02c-a87fa2e71832)

Chromium dark mode:
![image](https://github.com/schlagmichdoch/PairDrop/assets/52242352/22d9f665-189b-4ecf-aa61-b09cca8265ae)
 
What do you think?

**Comment by luckman212** [comment]
Yes the browser detection is neat but seems overly complex and a bit fiddly. I don't mind the high contrast icon at all. I suppose if it really bothers people it could be made into some kind of configurable environment variable?

```
-e FAVICON_URL="./whatever.ico"
```

**Comment by schlagmichdoch** [comment]
I‘d like to be consistent between self hosted versions and pairdrop.net.

So I will change the icon to the blue icon for the next version `v1.10.4` in the next days. Thanks for your input!

**Comment by luckman212** [comment]
Updated to 1.10.5 ... LGTM 🚀 

#### Light

<img width=413 src=https://github.com/schlagmichdoch/PairDrop/assets/1992842/0ceb7e0e-dd91-41c6-aeba-b9ecc9807b2f>

#### Dark

<img width=388 src=https://github.com/schlagmichdoch/PairDrop/assets/1992842/fb4aff6f-c28b-42d4-a1b5-05804c008c1b>
