### ISSUE TITLE
[Bug] PairDrop Siri Shortcut has broken UI

### ISSUE THREAD

**Issue by ghost** [schlagmichdoch/PairDrop#237]
**Describe the bug**
PairDrop's Siri Shortcut (to share from the iOS share menu) has been broken since the iOS 17.0 update. Sometimes it works, but other times the sharing window opens and takes up half of the screen instead of being in an overlay window like normal

**To Reproduce**
1. Install the PairDrop shortcut on iOS
2. Run the shortcut. 50/50 chance it breaks

**Expected behavior**
Normally, the shortcut should open a mini-window in Safari, like this: ![IMG_0600](https://github.com/schlagmichdoch/PairDrop/assets/80056225/3535de70-0f20-493d-a3d8-29c53f4e4edd)

**Screenshots**
![IMG_0599](https://github.com/schlagmichdoch/PairDrop/assets/80056225/6f88c264-929c-46c3-bbed-30be53b322eb)

**Smartphone**
 - Device: iPhone 12
 - OS: iOS 17.2.1
 - Browser: Safari
 - Version: Safari 17.2.1

**Bug occurs on official PairDrop instance https://pairdrop.net/**
No | **Yes**
Version: v1.10.3

**Additional context**
The bug is extremely inconsistent, as mentioned above

**Comment by schlagmichdoch** [comment]
Oh wow this looks indeed really strange.. I have no idea what could be the issue for this or how to reliably reproduce this.
Sadly the shortcuts app is known to be quite unreliable sometimes. Some articles online recommend restarting the iPhone but I believe you have tried that already.
I'm sorry but I don't know if there is anything we can do for this as this looks to be a glitch/bug of the shortcuts app itself.

We will have more control after releasing our own native clients #198 but this will probably take some time.

**Comment by schlagmichdoch** [comment]
See also #232

**Comment by schlagmichdoch** [comment]
I have since updated to iOS 17.2.1 and cannot reproduce this. Is this still an issue for you?

**Comment by schlagmichdoch** [comment]
So this is happening to me too. I could get rid of it by switching from opening PairDrop in a pop-up (webview) to opening PairDrop in Safari. 

@sov27 Could you please verify that this works for you reliably as well?
I will then update the routinehub repo if everything works as expected:
https://www.icloud.com/shortcuts/5182f0a3eb2f4826a188f8e1d5976126

**Comment by sov27** [comment]
Yeah, the issue disappears when the shortcut opens in Safari.

**Comment by schlagmichdoch** [comment]
Alright, thanks for testing! I have since noticed the webview bug is also present with other shortcuts, so I fully believe this is an iOS bug..

Until it is fixed, I will replace the shortcut with the Safari version.

**Comment by schlagmichdoch** [comment]
Apparently, there are more issues with the shortcuts app. If you take a look at the first comment of this thread it looks exactly like your screenshot:
https://www.reddit.com/r/shortcuts/comments/17koojf/action_show_web_view_at_bug/

**Comment by schlagmichdoch** [comment]
I have updated the RoutineHub shortcut to v1.4.2 which should solve this issue. Which behavior would you prefer once the web view action becomes reliable again? Opening in a web view (pop-up) or opening in Safari?
