### ISSUE TITLE
[Bug] Error `Invalid Group Specifier Name` on Safari

### ISSUE THREAD

**Issue by DAIL7069** [schlagmichdoch/PairDrop#239]
<img width="1475" alt="image" src="https://github.com/schlagmichdoch/PairDrop/assets/135861944/aeab8085-0601-40e6-bf48-55cd7111bf3b">It seems that there is a bug in the Safari browser and the website does not work properly. But edge is normal

**Comment by schlagmichdoch** [comment]
Not good. Thanks for reporting!
What version of safari do you use? 

Apparently, Safari only supports one specific part of the REGEX since version 16.4 https://caniuse.com/js-regexp-lookbehind

**Comment by DAIL7069** [comment]
> Not good. Thanks for reporting! What version of safari do you use?
> 
> Apparently, Safari only supports one specific part of the REGEX since version 16.4 https://caniuse.com/js-regexp-lookbehind

ios15.5,iphone13

**Comment by schlagmichdoch** [comment]
> ios15.5,iphone13

This is the version of your phone. What's the Safari version on your Mac? (Upper left corner `Safari` > `About Safari`

I fixed the issue that I mentioned. Please test whether there are any other issues on this instance: https://pairdrop-dev.onrender.com/

**Comment by DAIL7069** [comment]
> > ios15.5,iphone13
> 
> This is the version of your phone. What's the Safari version on your Mac? (Upper left corner `Safari` > `About Safari`
> 
> I fixed the issue that I mentioned. Please test whether there are any other issues on this instance: https://pairdrop-dev.onrender.com/

Safari version:15.6.1.There seems to be no problem.

**Comment by schlagmichdoch** [comment]
So instead of "Loading..." it shows a name and does not log any errors in the console?

**Comment by DAIL7069** [comment]
> So instead of "Loading..." it shows a name and does not log any errors in the console?

yes,no problem now.
