### ISSUE TITLE
[Enhancement] Warn user when TURN fallback 

### ISSUE THREAD

**Issue by Rudxain** [schlagmichdoch/PairDrop#249]
**What problem is solved by the new feature**
When the client fails to establish a LAN connection, it silently falls-back to using an internet connection. Users may notice the switch because of transfer speed. This is usually undesirable, as LAN is the main reason why users choose this app.

**Describe the feature**
There should be a small warning/status-icon that notifies the user if internet is being used.

Additionally, there could be an opt-in setting (persistent with cookies) that asks for confirmation before proceeding with TURN

**Comment by schlagmichdoch** [comment]
Duplicate of #181
