### ISSUE TITLE
Bug: Firefox on Android doesn't discover other devices

### ISSUE THREAD

**Issue by andreapx** [schlagmichdoch/PairDrop#25]
**Describe the bug**
Using Firefox on Android doesn't find other devices in the same network

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro
 - OS: Android 13
 - Browser: Firefox
 - Version: 109.2.0

**Additional context**
With Chrome on the same device it works

**Comment by andreapx** [comment]
Well, it is working now!
Today I'm at the office, yesterday I was at home, it could be possible that I had my VPN enabled.

**Comment by schlagmichdoch** [comment]
Thanks for testing again! Is it possible to get the browser log on Firefox on Android? I would be interested in the warnings it throws when you are connected to VPN and visit pairdrop.net, as PairDrop tries to warn users if WebRTC is not available.

FYI: If you self host, there is a fallback implemented if webrtc is not available that [can be enable via a flag](https://github.com/schlagmichdoch/PairDrop/blob/master/docs/host-your-own.md#websocket-fallback-for-vpn). As you need to trust the relay server this is not deployed on pairdrop.net

**Comment by andreapx** [comment]
I think that it's the same problem as the #26 . Without VPN everything works!
