### ISSUE TITLE
Remove extra back quote (`) from the command in documentation

### ISSUE THREAD

**Issue by lemonadeforlife** [schlagmichdoch/PairDrop#256]
As I've said in the title.
From the instruction of Nautilus context menu
https://github.com/schlagmichdoch/PairDrop/blob/3fa0873bc4f71f306f0f72afdfecc283bff75b85/docs/how-to.md?plain=1#L126-L129

**Comment by schlagmichdoch** [comment]
Well that was dumb, thanks for reporting!
Does everything else work as expected?
