### ISSUE TITLE
[Bug] URL not clickable

### ISSUE THREAD

**Issue by ueen** [schlagmichdoch/PairDrop#258]
send https://m.youtube.com/watch?v=xxxx and its not clickable after receiving

**Comment by schlagmichdoch** [comment]
Here we go again.. The problem seems to be the subdomain with a length of one (**m**.youtube.com)

I think I will loosen the REGEX. GitHub marks a lot of things as a URLs and let's the clients browser decide if the URL is valid or not.

To test this I'll add your link to the test group:
```
www.test
www.test.com
https://test.com
http://test.com
https://test.com?auth=token&si=123
https://onedrive.live.com/?authkey=%dfdsssdf7LJSM3w&id=88ADFF5%21285&cid=2DC78C46388A4354

**Comment by schlagmichdoch** [comment]
Please test whether everything works as expected: https://pairdrop-dev.onrender.com/

**Comment by schlagmichdoch** [comment]
I have tested the dev instance on a lot of devices and it seems to work just fine. I’ll merge it later
