### ISSUE TITLE
Bug: devices on dfferent networks pair but can't share

### ISSUE THREAD

**Issue by andreapx** [schlagmichdoch/PairDrop#26]
**Describe the bug**
When I pair 2 devices on different network the pairing seams to be working, but the device doesn't show on either browser

**To Reproduce**
1. open pairdrop on 2 devices that are on different networks
2. click on the link button on top right on both devices
3. insert the code visible on device 1 into device 2
4. the code disappears on both devices, so it seems that they have "seen" each other
5. the page stays "empty" and the other device doesn't show up

**Expected behavior**
After pairing I expect to see device 1 on browser 2 and device 2 on browser 1

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox/Chrome
 - Version: latest versions

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro
 - OS: Android 13
 - Browser: Firefox/Chrome
 - Version: latest versions

**Comment by schlagmichdoch** [comment]
I just tested this via Browserstack -> Pixel 7 -> Google Chrome and everything worked as expected. Could you try again?

**Comment by andreapx** [comment]
Well, it is working now!
Today I'm at the office, yesterday I was at home, it could be possible that I had my VPN enabled.
Thanks!

**Comment by andreapx** [comment]
I can confirm that with the VPN enabled it doesn't work.
Firefox console:

`WS: server disconnected [network.js:152:17](https://pairdrop.net/scripts/network.js)
Will-change memory consumption is too high. Budget limit is the document surface area multiplied by 3 (1185046 px). Occurrences of will-change over the budget will be ignored. [pairdrop.net](https://pairdrop.net/)
Database initialised. [ui.js:1395:21](https://pairdrop.net/scripts/ui.js)
Service Worker registered [ui.js:1604:21](https://pairdrop.net/scripts/ui.js)
WS: server connected [network.js:37:17](https://pairdrop.net/scripts/network.js)
WS: 
Object { type: "peers", peers: [], roomType: "ip", roomSecret: "" }
[network.js:63:42](https://pairdrop.net/scripts/network.js)
WS: 
Object { type: "display-name", message: {…} }
[network.js:63:42](https://pairdrop.net/scripts/network.js)
Request successful. Retrieved 0 room_secrets [ui.js:1514:29](https://pairdrop.net/scripts/ui.js)
Request successful. Retrieved key-pair: peerId - 6c6f019f-39d0-4041-9fa2-a81295be50ea [ui.js:1453:29](https://pairdrop.net/scripts/ui.js)
Request successful. Retrieved 0 room_secrets [ui.js:1514:29](https://pairdrop.net/scripts/ui.js)`
