### ISSUE TITLE
[Enhancement] Enable adding new translations on Hosted Weblate

### ISSUE THREAD

**Issue by BalazsSzeles** [schlagmichdoch/PairDrop#266]
**What problem is solved by the new feature**
Not having enough languages.

**Describe the feature**
According to [this article](https://docs.weblate.org/no/latest/devel/translations.html#adding-new-translations) admins of the [Hosted Weblate project](https://hosted.weblate.org/projects/pairdrop/) can enable [Adding new translations](https://docs.weblate.org/no/latest/admin/projects.html#component-new-lang) option in [Component configuration](https://docs.weblate.org/no/latest/admin/projects.html#component). This way anybody can suggest a new translation of a new language.

**Comment by schlagmichdoch** [comment]
Thanks for pointing out the possibility!
I have changed the setting to "Contact Maintainers" as I have to check whether the weblate language identifier equals the language identifier browsers return before translation can start. Is this enough?

**Comment by schlagmichdoch** [comment]
I have added Hebrew to translations and changed the setting again. Now, everyone can create a new translation and start translation right away. I have realized that the check with the language identifier can always be done at a later point.
