### ISSUE TITLE
[Bug] Duplicate "successful download" notification (Android app)

### ISSUE THREAD

**Issue by swanknight** [schlagmichdoch/PairDrop#299]
**Describe the bug**
Whenever I send a file from my PC to my tablet, I _always_ get two identical notifications from the Snapdrop app stating that the download was successful.

**To Reproduce**
1. Go to pairdrop.net 
2. Send file to tablet
4. See two notifications

**Expected behavior**
One notification is enough...

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 125.0.3 

**Smartphone (please complete the following information):**
 - Device: Lenovo Tab M8 HD
 - OS: Android 10
 - Browser: Not applicable
 - Version: Not applicable

**Bug occurs on official PairDrop instance https://pairdrop.net/**
Yes
Version: v1.10.8

**Bug occurs on self-hosted PairDrop instance**
No idea

**Self-Hosted Setup**
Proxy: Nginx | Apache2
Deployment: docker run | docker compose | npm run start:prod
Version: v1.10.8

**Additional context**
I'm using the official Snapdrop & Pairdrop Android app version 2.2.4 on my tablet.

**Comment by schlagmichdoch** [comment]
Does this also happen when using PairDrop itself (via a browser) or is this only an issue with the Android app?

**Comment by GrumpyEqualTrue** [comment]
> Does this also happen when using PairDrop itself (via a browser) or is this only an issue with the Android app?

It only happens when using the Android app.

**Comment by swanknight** [comment]
> Does this also happen when using PairDrop itself (via a browser) or is this only an issue with the Android app?

I don't normally use the browser to received files, but I just tested it with DuckDuckGo browser on my tablet, and it seems that this issue is isolated to the Android app.

**Comment by schlagmichdoch** [comment]
Thanks for testing!
Please move your issue to the Android app repository (which I am not maintaining): https://github.com/fm-sys/snapdrop-android

I guess the offline issue should be a separate issue over at the Android app repo
