### ISSUE TITLE
Bug:/Enhancement:/Feature Request: 

### ISSUE THREAD

**Issue by xundeenergie** [schlagmichdoch/PairDrop#30]
**Describe the bug**

The npm-version seems too old.
When i look into docker logs, i get this notice on startup:

```
node_1  | npm notice 
node_1  | npm notice New minor version of npm available! 9.3.1 -> 9.4.2
node_1  | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.4.2>
node_1  | npm notice Run `npm install -g npm@9.4.2` to update!
node_1  | npm notice 
```
In docker-complose.yml ist this `image: "node:lts-alpine"`

**Comment by schlagmichdoch** [comment]
This is not an issue of PairDrop.

I just checked and[ node:lts-alpine is currently pointing to node v18.14.0](https://hub.docker.com/_/node?tab=tags&page=1&name=lts-alpine).

If you see [this overview](https://nodejs.org/dist/index.json) that shows the linked npm version to a node version, you will find node v18.14.0 on position 8 that points to npm 9.3.1

I guess, they need to update their dependencies. Afterwords, node v18.14.0 will probably ship with npm 9.4.2 and this notice will not appear anymore
