### ISSUE TITLE
[Bug] Installation not successful

### ISSUE THREAD

**Issue by mucstudio** [schlagmichdoch/PairDrop#302]
After successful installation, when opened, the network keeps prompting: Connecting

You are aware as: Loading

**Comment by schlagmichdoch** [comment]
What do you mean with „after successful installation“? If you’re requesting help, you should at least fill in the template for bug reports:
https://github.com/schlagmichdoch/PairDrop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md

**Comment by schlagmichdoch** [comment]
Closing this as stale
