### ISSUE TITLE
[Enhancement] Document where I can load a signed ssl certificate

### ISSUE THREAD

**Issue by XmemphistoX** [schlagmichdoch/PairDrop#303]
**What problem is solved by the new feature**
What's the motivation for this topic
I'm not using a reverse proxy - Would like to provide a certificate to host it.

**Describe the feature**
Document a way to add my own trusted CA to sign it.

**Drafts**
Screenshots of Draw.io graph or drawn sketch.

**Additional context**
Add any other context here.

**Comment by schlagmichdoch** [comment]
I'm unsure what you mean. What do you need? Some kind of automatic certificate creation to load into your devices? How would that work without a reverse proxy?

**Comment by schlagmichdoch** [comment]
I'm still not sure what you mean, as certificates are handled by your reverse proxy (nginx or alike) and not by PairDrop itself.
Maybe you mean something like this: https://github.com/schlagmichdoch/PairDrop/blob/master/docs/host-your-own.md#local-development

Closing this as stale
