### ISSUE TITLE
web上不显示手机节点，无法建立链接

### ISSUE THREAD

**Issue by v587xpt** [schlagmichdoch/PairDrop#318]
我将PairDrop部署在了 192.168.1.88上，端口3000（使用docker运行的），在局域网内的其他电脑上，用浏览器访问 192.168.1.88:3000，web上都可以显示出来每个电脑节点，如：
![image](https://github.com/user-attachments/assets/392422e8-2883-46a5-81f1-b9030b9d0cdc)
局域网内的一个wifi路由器设备（192.168.1.188），我用手机连接了wifi，再通过浏览器访问 192.168.1.88:3000，无法和其他电脑上的节点建立链接，web上也不显示这个设备；是因为wifi路由器进行了NAT吗？导致它们互相搜索不到？
请求您的解答

**Comment by schlagmichdoch** [comment]
I’m sorry but I can only provide support if you switch to English.

**Comment by v587xpt** [comment]
I deployed a private PairDrop，Planned for use within the LAN。
Service port：192.168.1.88:3000
LAN computers can appear normally in Pairdrop，However, IOS connected to a wifi router cannot be scanned on Pairdrop and will not be displayed。
See the architecture diagram：
![image](https://github.com/user-attachments/assets/988c5ae8-eda1-4a6b-a57e-801c9ef48552)
The phone accessed 192.168.1.88:3000 through safari，PC accessed through chrome 192.168.1.88:3000，No iphone in sight；Is it because the wifi router NAT？

**Comment by haiking419** [comment]
我也遇到一样的问题，部署完之后，两台设备在同一网段，web上都可以显示出来每个节点，但是不同网络时，即便进行了设备永久配对，但web上还是没法看到对方节点
![image](https://github.com/user-attachments/assets/8a6a507f-0be8-4514-ba12-8aaa92024f79)
查看设备：
![image](https://github.com/user-attachments/assets/9a87a6de-f8ce-40c8-b0ef-d85520877439)

**Comment by haiking419** [comment]
> 我将PairDrop部署在了 192.168.1.88上，端口3000（使用docker运行的），在局域网内的其他电脑上，用浏览器访问 192.168.1.88:3000，web上都可以显示出来每个电脑节点，如： ![image](https://private-user-images.githubusercontent.com/37898515/354105828-392422e8-2883-46a5-81f1-b9030b9d0cdc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NzE2NjYsIm5iZiI6MTcyMzc3MTM2NiwicGF0aCI6Ii8zNzg5ODUxNS8zNTQxMDU4MjgtMzkyNDIyZTgtMjg4My00NmE1LTgxZjEtYjkwMzBiOWQwY2RjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDAxMjI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5Nzg1YTYyMThkODJiMTI4ZDAwYTA4MjkzOGRmMjc5M2QzN2JhZWJlNDFhZDUwNzczODcxNDI3NmMwZDMwZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FUHhUrvnlxtfJL53JoTGtXj5F1k4eRgg4NUptt3lqws) 局域网内的一个wifi路由器设备（192.168.1.188），我用手机连接了wifi，再通过浏览器访问 192.168.1.88:3000，无法和其他电脑上的节点建立链接，web上也不显示这个设备；是因为wifi路由器进行了NAT吗？导致它们互相搜索不到？ 请求您的解答

我也碰到类似的问题

**Comment by schlagmichdoch** [comment]
> Is it because the wifi router NAT？

I believe so. Try to deploy a turn server alongside it: https://github.com/schlagmichdoch/PairDrop/blob/master/docs/host-your-own.md#turn-server-for-internet-transfer

**Comment by schlagmichdoch** [comment]
Also, starting in `v2.0.0` the websocket fallback will be a fallback for all connections that fail otherwise if no turn server is specified. You would then start PairDrop with the env var `WS_FALLBACK=true`. I recommend to use a turn server though for speed and security purposes.

**Comment by 61456421** [comment]
我的也是这情况，你解决了吗
