### ISSUE TITLE
[Bug] Name input isn't intuitive to use

### ISSUE THREAD

**Issue by bt90** [schlagmichdoch/PairDrop#319]
**Describe the bug**

Maybe it's just me, but the name input is far from intuitive.

![image](https://github.com/user-attachments/assets/66d9e233-8052-4051-8139-4314cbc3fdcc)

As a new user the input looks like a non-editable label at first glance. Visually it's closer to Githubs presentation of labels and you wouldn't expect to be able to edit this text:

![image](https://github.com/user-attachments/assets/a2afef60-1eb3-4d53-bf16-d835add393a3)

Since the actual input does not seem to be editable, the "edit button" next to it must be there to toggle it. At least that was my thought.

As nothing happened after clicking the image that I misidentified as a button, I revised my previous assumption and tried to use the input by clicking in it. The barely or even invisible cursor adds to that confusion:

Firefox:

![image](https://github.com/user-attachments/assets/1bac5af1-1ada-4900-bd53-0511a2fffa3f)

Chrome:

![image](https://github.com/user-attachments/assets/64a622bc-b2fc-4014-a064-5d6ab1ecd306)

**Expected behavior**

I can see two possible solutions:

1. use a text input with less styling and a working curosr so that the user can visually identify it as such
2. keep the current styling but implement a toggle mechanism by treating the pen icon as a button. This way we can have the nicely styled label and use a regular input when editing

**Comment by schlagmichdoch** [comment]
Thanks for your input!
The edit pen icon is styled in such a way that clicking it focuses the input field as is expected by an edit button.

I like the current design as it is optimized for mobile:
1. Tap either on the name itself or on the edit pen icon
2. The keyboard opens up
3. Type in the new name
4. Close the keyboard / press enter / tap somewhere else
5. The name is changed

I agree that it might be less intuitive for new users on Desktop browsers as there is no keyboard to pop up.

Ideas to make it more intuitive:
- As soon as the input field is focused, change the badge to a white background with grey border with a visible cursor to make clear that it's an editable input field now
- Increase the contrast by switching to a darker gray

Any other ideas?

**Comment by bt90** [comment]
I think the missing cursor is the biggest offender to be honest. At least on Firefox you get no real feedback.

I guess the autogenerated name isn't really set as content and rather as a placeholder? Because as soon custom text is entered, things are working as expected:

![image](https://github.com/user-attachments/assets/c963969c-3beb-42d7-b5e5-6527aad6d2f6)

![image](https://github.com/user-attachments/assets/47eb05e0-d9af-4fc7-8811-2f2aec22f522)

**Comment by bt90** [comment]
Could we fill in the input instead of using a placeholder? Clicking the edit button should focus on the input and select the entire text. That should be enough to make desktop users happy and keep things slick on mobile.

**Comment by bt90** [comment]
Ah! It's not an input at all:

![image](https://github.com/user-attachments/assets/bfe66404-b550-4f17-b326-0bf5f82e3790)

Switching to a proper text input might solve our problems.

**Comment by bt90** [comment]
The contenteditable div seems to trigger a known Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=904846

**Comment by schlagmichdoch** [comment]
I don’t think it has anything to do with the node type. Also, the Firefox bug seems to only impact nodes with a `::before` pseudo-element which we do not use.

The current behavior (apart from the missing cursor) is by design but seems to be unintuitive for you so I’m open to change it.

I’ll increase the contrast and try to force the cursor to be clearly visible on all platforms.

If things are working as expected for you as soon as text is entered, we could simply clear the placeholder field if the name node is focused.
Then, clicking the node or the edit icon focuses the text field and the random name gets hidden which should be enough to indicate to the user, that they can simply type a name now.

Alternatively, we could add „Custom Name“ to it if clicked and select it. This way it is clearer that it’s a text field and as soon as something is typed „Custom Name“ is overwritten.

Although the first idea removes the hint, that leaving the name empty resorts to it being random again, I prefer it to the second idea. What do you think?

**Comment by bt90** [comment]
> I don’t think it has anything to do with the node type. Also, the Firefox bug seems to only impact nodes with a `::before` pseudo-element which we do not use.

This may be an implicit behavior. At least Firefox shows the `::before` for this div in the inspector:

![image](https://github.com/user-attachments/assets/f16da6ed-05db-415b-a829-f6dec9ba7a4e)

Switching from `<div>` to `<input>` would fix this. At least judging by a quick experiment manipulating the DOM from the Firefox developer console.

It's also a bit cleaner from a semantic point of view.

> we could simply clear the placeholder field if the name node is focused.

Much appreciated. I think this can be done with plain CSS:

```css
input:focus::placeholder {
  color: transparent;
}
```

**Comment by bt90** [comment]
Minimal CSS to restore most of the look:

```css
input:focus::placeholder {
  color: transparent;
}
input::placeholder {
  font-family: "Open Sans", -apple-system, BlinkMacSystemFont, sans-serif;
  line-height: 20px;
  opacity: 1;
  font-weight: 400;
}
```

div:

![image](https://github.com/user-attachments/assets/b125e2ec-f8fc-4136-aece-6e2d7180121a)

input:

![image](https://github.com/user-attachments/assets/4590db3e-e62c-47fe-952d-cf749bc184bd)

input:focus:

![image](https://github.com/user-attachments/assets/9664acbc-965a-4a08-83dc-0fba4cbd91a9)

**Comment by schlagmichdoch** [comment]
You were too fast! I corrected my mistake one minute earlier.

Anyways, apparently Firefox cursor position is broken whenever the div is completely empty:
![Screenshot from 2024-08-07 13-40-05](https://github.com/user-attachments/assets/45b5a48e-3492-4783-ac64-9d7a0991e611)

Probably, this is why they always add a line break to a div whenever text is deleted which I needed to work around in the current design:
https://github.com/schlagmichdoch/PairDrop/blob/a68cd75b715d62f46192ac2e3cef6000eca37114/public/scripts/ui-main.js#L262-L265

I'll play around a little and come up with a solution

**Comment by bt90** [comment]
I'm curious but why is a `<div>` used here?

**Comment by schlagmichdoch** [comment]
> I'm curious but why is a `<div>` used here?

While a div is just a plain container an input node is rendered differently on every OS and browser. As you have experienced earlier we would have to reset the default input css first before adding our own. I prefer to start with a clean canvas.

![table](http://man.hubwiz.com/docset/HTML.docset/Contents/Resources/Documents/mdn.mozillademos.org/files/4273/all-single-line-text-field.png)
http://man.hubwiz.com/docset/HTML.docset/Contents/Resources/Documents/developer.mozilla.org/en-US/docs/Web/Guide/HTML/Forms/The_native_form_widgets.html#Single_line_text_fields

While this is old it brings the point accross, I think.

As PairDrop is a web app, I'd like to have as much control on its look as possible.

---

I have implemented a fix. Please this on different browsers: https://pairdrop-next.onrender.com

**Comment by bt90** [comment]
> While a div is just a plain container, an input node is rendered differently on every OS and browser.

Thanks for the insight. Sounds reasonable :slightly_smiling_face: 

> I have implemented a fix. Please test this on different browsers: https://pairdrop-next.onrender.com

Just gave it a try on Firefox and Chrome. Both browsers now behave similarly and the user feedback is much better IMHO.

One nitpick:

1. enter a custom name
2. select the text or parts of it
3. click anywhere else
4. the text remains selected

![image](https://github.com/user-attachments/assets/885aea35-1de3-421d-8032-acf5b62c2deb)

**Comment by bt90** [comment]
Can we switch the background color to e.g `#33333` ? This would improve the contrast and would match the color of the current icon set:

![image](https://github.com/user-attachments/assets/0c7abef1-339a-4780-ac18-60d9ffacdcf9)

**Comment by schlagmichdoch** [comment]
That's too dark for my liking but I see your point. I propose `#757575` which sits somewhere in the middle and passes your WebAIM AA rating with 4.6:1 and looks good on light and dark mode:

<img src="https://github.com/user-attachments/assets/a36bc37c-4a9a-4a82-8f95-e62c42da9296" width=400 />

<img src="https://github.com/user-attachments/assets/863a9361-4904-4c7c-be22-feab7a1d7f05" width=400 />

---



> One nitpick:
> 
>     1. enter a custom name
> 
>     2. select the text or parts of it
> 
>     3. click anywhere else
> 
>     4. the text remains selected

Good catch! New try: https://pairdrop-next.onrender.com

**Comment by bt90** [comment]
Beautiful!

One last thing I noticed is that the name tends to get applied prematurely in Firefox:

* enter a custom name for the first time -> erratic apply after X ms without typing (?)
* edit an existing custom name -> nothing

It also feels a little different in Firefox and Chrome. Maybe the focus is somehow lost?

**Comment by schlagmichdoch** [comment]
I cannot reproduce this. Is this still an issue? Could you capture a screencast of it?

**Comment by bt90** [comment]
Weird. It's working now :shrug: 

The only thing missing is the color change.

**Comment by schlagmichdoch** [comment]
Perfect! I'll push the color change then and will release it as part of the next minor version `1.10.10`

**Comment by schlagmichdoch** [comment]
I just released the newest version and deployed it on pairdrop.net. Thanks for your help! :)
