### ISSUE TITLE
[Bug] Problems with Edge Browser on macOS

### ISSUE THREAD

**Issue by Leonscrt** [schlagmichdoch/PairDrop#320]
**Describe the bug**
The user cannot be found in the Edge browser, both on macOSX and Windows 11

**Comment by schlagmichdoch** [comment]
Please provide more information as requested via the bug issue template:
- How to reproduce
- Screenshots
- pairdrop.net or self-hosted

Also: what exactly does not work? Autodiscovery? Pairing? Public rooms?

**Comment by Leonscrt** [comment]
How to reproduce ：As long as one of the two devices is the Edge browser on Windows 11 or Mac OS X, neither will be able to Autodiscovery the other；

pairdrop.net or self-hosted：pairdrop.net；

what exactly does not work? Autodiscovery? Pairing? Public rooms?：Autodiscovery ，Pairing ，not work。

**Comment by schlagmichdoch** [comment]
Does autodiscovery of two browser tabs on the same device work?

This might be caused by Mac’s iCloud private relay. Do you have it enabled? 
https://support.apple.com/de-de/guide/mac-help/mchlecadabe0/mac

**Comment by Leonscrt** [comment]
In Mac OS X, chrome and edge on the same device can discover each other, and edges on the same device can also discover each other. However, Safari and Chrome and Edge under the same device cannot be discovered by each other. When I use the edge browser for ios, I can discover the safari users of Mac OS X but not the edge users of Mac OS X.

I didn't open it。

**Comment by schlagmichdoch** [comment]
I cannot reproduce this. When using pairdrop.net on MacOS Edge, Chrome, and Safari everything works as expected.

You must specify the steps to reproduce this (1. 2. 3.)  otherwise I cannot help you to resolve this.

**Comment by Leonscrt** [comment]
The problem seems to be gone, thanks for the work, it's a great tool to use。

**Comment by schlagmichdoch** [comment]
Awesome! Take care!

**Comment by Leonscrt** [comment]
The problem recurs, in the latest version of Windows 11 and mac OS X, the edge browser pairdrop.net cannot be found in the same operating system and cannot be found in the same operating system。

Mac OS X
<img width="1680" alt="截屏2024-08-29 下午12 32 12" src="https://github.com/user-attachments/assets/4c84bc44-ab91-4af9-9661-dbba56c37ba7">

Windows11
<img width="1680" alt="截屏2024-08-29 下午12 32 28" src="https://github.com/user-attachments/assets/8a54d373-03da-46da-a82f-3a637f10a3bb">
