### ISSUE TITLE
[Bug] iPhone 11 Pro IOS 15.3.1 isn't discoverable, name stays as "Loading"

### ISSUE THREAD

**Issue by Bristopher** [schlagmichdoch/PairDrop#339]
**Describe the bug**
When using a iPhone 11 Pro IOS 15.3.1 (on cellular data and WiFi) both my public self hosted instance and pairdrop.net never let it become discoverable it just stays saying "You are known as: Loading..." and "You can be discovered: on this network". 

Even if I enter a custom name it still doesn't make me discoverable on other devices. Also clicking the pair/link button does nothing but highlight/unhighlight the button along with the "Join public room temporarily" button, which I believe to this version of IOS not supporting dialogs (broke with 1.8.0(buttons working 1.7.7) release from https://github.com/linuxserver/docker-pairdrop/pkgs/container/pairdrop). A Long time ago I had no issue whatsoever, but I recently updated it months ago and now am having this issue, unfortunately I don't know the last version it was functioning on. 

**To Reproduce**
1. Use iPhone 11 Pro on IOS 15.3.1
2. Go to self hosted url or pairdrop.net
3. You aren't discoverable and never auto generate a name

**Expected behavior**
You're supposed to have a name auto generated and be seen by other on the same network, and pairing/linking functionality should work to be discoverable.

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: IOS 
 - Browser: Safari, Safari Private Browsing, Chrome
 - Version 15.3.1

**Bug occurs on official PairDrop instance https://pairdrop.net/**
Yes
Version: v1.10.10

**Bug occurs on self-hosted PairDrop instance**
Yes
Version: v1.10.10

**Self-Hosted Setup**
Proxy: Nginx Proxy Manager
Deployment: Unraid Docker
Version: v1.10.10

**Additional context**
- It seems to be because it gets stuck waiting for async hydrate() to finish. The bug is somewhere in "this.server = new ServerConnection();" and before "Loading config..." gets logged.
- Going back to version 1.0.0 (https://github.com/linuxserver/docker-pairdrop/pkgs/container/pairdrop) I at least get assigned a name but I'm still not discoverable, I'm only discoverable on another tab on my iPhone
- My iPhone isn't using a vpn (even if I do use a vpn to my home network it doesn't work), has no extra DNS configured, and I tried turning off private address / Limit IP Address Tracking but no still not discoverable.
- If I enable DEBUG_MODE every time I go to my self hosted instance it logs "----DEBUGGING-PEER-IP-START----", but when I load the website on my iPhone is doesn't log anything

IOS Chrome console logs
https://pairdrop.net/
Service Worker registered
Database initialised.
Page successfully translated System language: en Selected language: en
Initial translation successful.
Request successful. Retrieved 0 room_secrets
Load deferred assets...
Stylesheet loaded successfully: styles/styles-deferred.css
Script loaded successfully: scripts/util.js
Script loaded successfully: scripts/browser-tabs-connector.js
Script loaded successfully: scripts/network.js
Script loaded successfully: scripts/ui.js
Script loaded successfully: scripts/qr-code.min.js
Script loaded successfully: scripts/zip.min.js
Script loaded successfully: scripts/no-sleep.min.js
Script loaded successfully: scripts/heic2any.min.js
Loading of deferred assets completed.
Hydrate UI...

My self hosted instance logs:
https://pairdrop.customdomain.com/
Upgrading IndexedDB database from version 0 to version 5
Page successfully translated System language: en Selected language: en
Initial translation successful.
Database initialised.
Request successful. Retrieved key-pair: editedDisplayName - undefined
Service Worker registered
Request successful. Retrieved 0 room_secrets
Load deferred assets...
Stylesheet loaded successfully: styles/styles-deferred.css
Script loaded successfully: scripts/browser-tabs-connector.js
Script loaded successfully: scripts/util.js
Script loaded successfully: scripts/network.js
Script loaded successfully: scripts/qr-code.min.js
Script loaded successfully: scripts/ui.js
Script loaded successfully: scripts/zip.min.js
Script loaded successfully: scripts/no-sleep.min.js
Script loaded successfully: scripts/heic2any.min.js
Loading of deferred assets completed.
Hydrate UI...

If I change my display name and reload:
Request successful. Retrieved key-pair: edited_display_name - undefined
Request successful. Added key-pair: edited_display_name - cow

Service Worker registered
Database initialised.
Page successfully translated System language: en Selected language: en
Initial translation successful.
Request successful. Retrieved 0 room_secrets
Load deferred assets...
Script loaded successfully: scripts/util.js
Script loaded successfully: scripts/network.js
Stylesheet loaded successfully: styles/styles-deferred.css
Script loaded successfully: scripts/qr-code.min.js
Script loaded successfully: scripts/ui.js
Script loaded successfully: scripts/zip.min.js
Script loaded successfully: scripts/no-sleep.min.js
Script loaded successfully: scripts/heic2any.min.js
Script loaded successfully: scripts/browser-tabs-connector.js
Loading of deferred assets completed.
Hydrate UI...

**Comment by Monoxide8969** [comment]
I don't know if it's related, but latest Ios doesn't pair with latest macos either (safari)

**Comment by schlagmichdoch** [comment]
@Monoxide8969 probably not related. Please issue another bug report with separate logs.

@Bristopher Sorry for the delay!
I believe this is due to BroadcastChannel only being available since iOS 15.4.
Is this resolved on this test instance on your devices?
https://pairdrop-dev.onrender.com

**Comment by Bristopher** [comment]
> @Monoxide8969 probably not related. Please issue another bug report with separate logs.
> 
> @Bristopher Sorry for the delay! I believe this is due to BroadcastChannel only being available since iOS 15.4. Is this resolved on this test instance on your devices? https://pairdrop-dev.onrender.com

That resolved it! It works on the test instance.

**Comment by schlagmichdoch** [comment]
Great, thanks for testing! It will be part of the next update which will be deployed this week. I'll notify you here

**Comment by Bristopher** [comment]
Thank you!!!
