### ISSUE TITLE
[Bug] how to install

### ISSUE THREAD

**Issue by baby68** [schlagmichdoch/PairDrop#347]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Bug occurs on official PairDrop instance https://pairdrop.net/**
No | Yes
Version: v1.10.10

**Bug occurs on self-hosted PairDrop instance**
No | Yes

**Self-Hosted Setup**
Proxy: Nginx | Apache2
Deployment: docker run | docker compose | npm run start:prod
Version: v1.10.10

**Additional context**

**Comment by schlagmichdoch** [comment]
See https://github.com/schlagmichdoch/PairDrop/blob/master/docs/host-your-own.md
