### ISSUE TITLE
[Bug] Sharing form gallery on Android not working

### ISSUE THREAD

**Issue by Boerny41** [schlagmichdoch/PairDrop#354]
**Describe the bug**
When going to the gallery, selecting an image, clicking share and then pairdrop the app opens. When then selecting the target it brings up a menu and asks me if I want to open the camera app, own files or another app instead of sharing the already selected picture.

**To Reproduce**
1. Go to gallery
2. Click on share, pairdrop
3. Select the target
4. Get asked what App to open

**Expected behavior**
The selected image should get shared

**Screenshots**
No screenshots due to sensitive data showing up in them.

**Smartphone (please complete the following information):**
 - Device: Samsung S21 FE
 - OS: Android 14, One UI 6.1
 - Browser: Samsung Browser (used to install the PWA)
 - Version: 27.0.0.79

**Bug occurs on self-hosted PairDrop instance**
Yes, v1.10.10

**Self-Hosted Setup**
Proxy: none, local only
Deployment:docker compose
Version: v1.10.10

**Comment by schlagmichdoch** [comment]
Does this happen on pairdrop.net as well?

Have you deployed your instance via https? I believe for PairDrop to be registered as file handler on Android it needs to be served on a secure environment meaning https. After you have upgraded your instance to https you might need to reinstall the pwa for the os to register it.

**Comment by Boerny41** [comment]
With https it now works perfectly, thank you!
