### ISSUE TITLE
Indicate if a new file has been received

### ISSUE THREAD

**Issue by Myzel394** [schlagmichdoch/PairDrop#4]
It'd be cool to see some kind of indication when the tab has received a file, because sometimes you have a lot of tabs open and search for the correct one. I'd suggest to change the color of the tab icon.

E.g. original

![android-chrome-512x512](https://user-images.githubusercontent.com/50424412/213295328-073710d7-5ced-4a27-9f1a-3a08b0183185.png)

indicator icon

![android-chrome-512x512](https://user-images.githubusercontent.com/50424412/213295668-ef67da83-6e0e-4d5c-9cca-e36c6d9a15b7.png)

**Comment by schlagmichdoch** [comment]
I like the idea of indicating that a message / file was received.
I would like to stick with the icon as it is as blue is the signature color of PairDrop.

[This website](https://webdesign.tutsplus.com/tutorials/how-to-display-update-notifications-in-the-browser-tab--cms-23458) suggests to change the document.title instead:
When the ReceiveFileDialog is shown, the tab title would change from `PairDrop` to `(3) PairDrop` with the number of files in brackets.
When the ReceiveTextDialog is shown, the tab title would change from `PairDrop` to `(1) PairDrop`.

What do you think?

**Comment by Myzel394** [comment]
I think a red dot would fit as I often have more than 1000+ tabs open so that I don't see the title anymore. To change the title is a great idea, many websites use that already so users will probably know what it means

**Comment by schlagmichdoch** [comment]
True. There is also the pinning feature on firefox which completely hides the title. 
![Screenshot 2023-01-19 173447](https://user-images.githubusercontent.com/52242352/213499905-bd092996-36c3-4dd1-96cf-36e21696a3d9.png)

So probably I will implement both ideas

**Comment by schlagmichdoch** [comment]
The current implementation works on Firefox.

On Edge only the tab title is changed but the favicon is not changed. It is working on this website: https://mathiasbynens.be/demo/dynamic-favicons so I give it another look

**Comment by schlagmichdoch** [comment]
It's working now 🦾
