### ISSUE TITLE
Enhancement: show a warning if "WS_FALLBACK=true" is enabled on a self-hosted instance

### ISSUE THREAD

**Issue by ovizii** [schlagmichdoch/PairDrop#41]
Since this is less secure and traffic passes through the server (if I understood your warning correctly) it would be nice to see a warning when this feature is set OR, even more awesome, only if it is being used.

**Comment by schlagmichdoch** [comment]
if I understand you right this is both already implemented. There is a warning that the possibility is switched on and peers that are connected via this ws relay are shown with a red border
