### ISSUE TITLE
[Improvement] Larger QR code

### ISSUE THREAD

**Issue by zhdenny** [schlagmichdoch/PairDrop#43]
When clicking the pair button, a QR Code image is shown in addition to a Pairing Code.

Can this QR Code image be larger so it is easier for a guest to scan with their phone? It is pretty small currently. This is true in Both the desktop web view or mobile view.

This improvement would make it much easier to quickly pair devices...and that's kinda the point of a tool like this. Quick/Easy/Secure access

**Comment by schlagmichdoch** [comment]
Which device did you use to present the QR Code with?

It's important to keep it possible to use the feature on small displays.

How big would be big enough? 

Samsung S20:
<img src='https://user-images.githubusercontent.com/52242352/220932038-57549fd6-bcfe-4dc7-b2b7-9dc9f982185c.png' width='180'> <img src='https://user-images.githubusercontent.com/52242352/220932046-ea99a360-3670-4abd-a2d8-325fd38b979a.png' width='180'> <img src='https://user-images.githubusercontent.com/52242352/220932051-b0cf9766-7bf9-4035-968b-6654f09a7938.png' width='180'>
<img src='https://user-images.githubusercontent.com/52242352/220933476-90e62cec-3fa2-447b-b8a1-a472884b6c89.png' width='180'> <img src='https://user-images.githubusercontent.com/52242352/220932058-1fff7fa0-6be9-4c0d-b85f-2acdf7e5cb9c.png' width='180'>

**Comment by zhdenny** [comment]
I understand the QR code needs to be sized small enough to fit on small displays (like phones).

Usually, websites are resized when viewed via Mobile or Desktop. I can see this is the case with PairDrop in a lot of ways....except the QR Code. Can the QR code be one size in Mobile webview and a larger size in Desktop webview? Just a thought because the QR Code is incredibly small when viewed on a typical Desktop web browser. When scanning that QR code with a phone I actually have to zoom the camera in pretty far to pick it up.

I frankly feel like the QR Code is even small on a Phone Display too though. This is a screenshot from my Pixel 7 device. That QR code is tiny if you think of the size of a phone.


![Screenshot_20230223-111129](https://user-images.githubusercontent.com/26662131/220968352-43a984e5-3727-476d-b984-070455eb4b6c.png)

**Comment by schlagmichdoch** [comment]
Probably the problem is bigger on desktop as the resolution is higher and therefor the QR code appears smaller.

I suggest making the QR code size 5 on Desktop and size 4 on mobile. What do you think?

**Comment by zhdenny** [comment]
I don't know what those numbers mean...sorry.

**Comment by schlagmichdoch** [comment]
My bad, I mean the images posted before!

zhdenny ***@***.***> schrieb am Do. 23. Feb. 2023 um 18:37:

**Comment by zhdenny** [comment]
Seems fine I guess.

**Comment by schlagmichdoch** [comment]
This is implemented by 0eb13d9 and live on pairdrop.net

**Comment by schlagmichdoch** [comment]
The following comments were deleted by GitHub (via hubot) as part of [mistakenly marking this account as spam on 17th February 2024](https://github.com/schlagmichdoch/PairDrop/issues/284). The correct thread order and the creation date is unclear. I decided to manually restore them anyway in order to complete the information this issue holds even though the restored information might be outdated:

Comment by @schlagmichdoch:
---

This is implemented by 0eb13d9 and live on pairdrop.net
