### ISSUE TITLE
Bug:Share button doesn't work on Android after receiving a file

### ISSUE THREAD

**Issue by saadbruno** [schlagmichdoch/PairDrop#48]
**Describe the bug**
When you receive a file on android, you get a pop up asking "close" or "share". Tapping "share" doesn't do anything.
Seems like it only happens with bigger files.
I tried sending an 80kb file and it worked fine. It didn't work with a 70mb video (video was mp4 h264 so the phone should be able to handle it no problem)

**To Reproduce**
1. Receive a file on Android
2. Tap on share
3. Nothing happens

**Expected behavior**
You should be able to open the share menu, or at least download the file.  
To be fair, I'd rather have PairDrop download files by default, instead of opening the share menu.

Maybe we could have a pop up with 3 buttons: "Close / Share / Download"

**Screenshots**

https://user-images.githubusercontent.com/23201434/221225226-f54035f3-b729-433a-9221-0223aa8e9bbb.mp4
In this recording, i got the "reconnecting" pop up and whatnot, but it doesn't seem related. I tried again and got the same issue.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Chrome 110.0.5481.105

**Smartphone (please complete the following information):**
 - Device: Samsung A72
 - OS: Android 12
 - Browser: Chrome (I actually installed the PWA, so I assume it's chrome)
 - Version: Chrome 110.0.5481.65

**Self-Hosted**
No

**Additional context**
I can upload the video file if needed, but seems reproducible with any bigger file

**Comment by schlagmichdoch** [comment]
Thanks for your issue. I will try to find out what happens with big files when sharing. 

I implemented the share menu to make it possible to save images directly to the gallery without saving them to downloads first but I like your idea of giving the user two options. They need to be tidy and clear though.

**Comment by schlagmichdoch** [comment]
> Maybe we could have a pop up with 3 buttons: "Close / Share / Download"

This is now implemented. Would be great if you could test it again and give feedback!

**Comment by schlagmichdoch** [comment]
@saadbruno Can we close this issue?

**Comment by saadbruno** [comment]
Sorry, busy week! I'll double check tonight! 

Thanks for implementing this!

**Comment by saadbruno** [comment]
> @saadbruno Can we close this issue?

Seems great! Worked flawlessly with 1.7 GB of video files
Thanks a lot

**Comment by saadbruno** [comment]
yea, share button still hangs. But I'm pretty sure it's Android's fault.

**Comment by schlagmichdoch** [comment]
Allright! As the share button is mostly for images anyway I guess it won't be a problem so much if people only have the possibility to download. Thanks for checking again!
