### ISSUE TITLE
Bug: Sharing via CLI doesn't work on Firefox

### ISSUE THREAD

**Issue by ChaosExAnima** [schlagmichdoch/PairDrop#62]
**Describe the bug**
The web app relies on the Clipboard API's [`readText`](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/readText) method. Unfortunately, this method is not [available in Firefox except inside browser extensions](https://caniuse.com/?search=clipboard.readText).

Maybe instead of just failing it could display an autoselected textarea element to paste the text into? 

**To Reproduce**
1. Either share a larger file via the CLI or open the Pairdrop webpage with `?base64zip=paste` appended in Firefox
2. Click the button that says "Tap here to paste files"
3. Button vanished and popup appears that says "This feature is not available on your browser."

**Expected behavior**
The base64-encoded file is loaded into Pairdrop

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.2.1
 - Browser: Firefox 
 - Version: 110.0.1

**Self-Hosted**
Yes, but issue occurs on pairdrop.net as well.

**Self-Hosted Setup**
Proxy: Traefik 2.9
Deployment: docker compose/swarm

**Additional context**
None

**Comment by schlagmichdoch** [comment]
While this is true, caniuse.com leaves out the possibility to enable the readText method of the asynchronous clipboard api  by setting `dom.events.asyncClipboard.readText` to true under `about:config`.
For me everything has worked as expected since.

I’m not sure but I believe Firefox will soon enable the feature by default. Not sure whether it’s enough to simply mention this workaround in the FAQ. What do you think? :)

**Comment by ChaosExAnima** [comment]
Didn't know that bit, cool- can confirm it works now. But I wouldn't expect FF to do it soon- Mozilla works at their own speed, after all. Hopefully they will, this is a good API to have available!

**Comment by schlagmichdoch** [comment]
So adding to FAQ is enough then?

**Comment by ChaosExAnima** [comment]
Personally I'd fix it? Like I suggested if the system detects the Clipboard API isn't available it can just display a textarea for the user to paste into and triggering based on a change event there... but if you don't want to maintain that a FAQ would work.

**Comment by schlagmichdoch** [comment]
> if the system detects the Clipboard API isn't available it can just display a textarea for the user to paste into and triggering based on a change event there

Good idea! I've done exactly that. Would appreciate, if you could have a look at #65 before I merge it :)

**Comment by ChaosExAnima** [comment]
Approved! Thanks for being so fast to fix this 🙂
