### ISSUE TITLE
Bug: cancelling "clear all paired devices" still clears them

### ISSUE THREAD

**Issue by ovizii** [schlagmichdoch/PairDrop#67]
**Describe the bug**
 cancelling "clear all paired devices" still clears them

**To Reproduce**
1. Go to pairdrop.net on two different devices on two different networks
2. Pair the two devices
3. Click on "clear all paired devices" on one of the two devices
4. In the pop-up select cancel
5. The result: all paired devices are cleared

**Expected behavior**
Selecting cancel does cancel the clearing of paired devices.

**Screenshots**
![image](https://user-images.githubusercontent.com/837902/223118967-5bf6d3b6-500c-4896-b5d1-f503a1d05166.png)

clicking cancel results in:
![image](https://user-images.githubusercontent.com/837902/223119024-7f6e3ea6-86ef-4e0a-808b-21d10be33ab6.png)

**Self-Hosted**
Yes

**Comment by schlagmichdoch** [comment]
Duh, html is weird: eventhough there is a button with `type="submit"` clicking any button in a form submits it if the button is not explicitly specified to be `type="button"`. This is fixed in `v1.4.4`

**Comment by ovizii** [comment]
thx!
