### ISSUE TITLE
Bug: High CPU Load

### ISSUE THREAD

**Issue by MMMZZZZ** [schlagmichdoch/PairDrop#75]
**Describe the bug**
Simply opening https://pairdrop.net causes about 50% CPU load in Firefox. Or, in other terms: +30W CPU power consumption and +7W iGPU power consumption.
In MS Edge it's less severe with "only" ~10% additional CPU load (resulting in +10W CPU and + 1.5W GPU power consumption), but still more than enough to make the fans ramp up - and much more than I'd expect. 

**Expected behavior**
No excessive CPU load.

**Screenshots**
Note: Both the jumps in CPU and GPU load come from opening PairDrop. The high network load is unrelated. 
![image](https://user-images.githubusercontent.com/36891873/224485136-630a4b3d-0087-4689-8ff7-142056bd2f74.png)

Same test with Microsoft Edge. Less severe but still noticeable CPU load. GPU load looks similar, but according to CoreTemp it's much less significant, too. 
![image](https://user-images.githubusercontent.com/36891873/224485451-770475af-b3bd-4f96-b706-f0ad56b2c45c.png)

**Desktop (please complete the following information):**
- OS: Windows 11 Pro 22H2, Build 22621.1265
- Hardware: MSI Creator 17 B11UE
  - Processor: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz   2.30 GHz
  - Installed RAM: 32,0 GB
 - Browser: Firefox 110.0.1 x64 | Microsoft Edge 110.0.1587.69 x64
 - Other: Core Temp 1.17.1
 - Version: Not sure what's meant...?

**Self-Hosted**
No

**Additional context**
I'm pretty sure this wasn't an issue a few days ago - or at least not as much of an issue. I remember using it to transfer some pictures to my computer and I'm pretty sure the fans did not ramp up that day. Unfortunately I can't remember when exactly that was. 
Opening the page in a private window does not solve the issue.

**Comment by schlagmichdoch** [comment]
I guess this is related to the way Snapdrop implemented the background animation. I wanted to rewrite the background animation for PairDrop anyway as there seems to be an issue with it getting speed up really fast sometimes.

As the background animation stops as soon as a device is connected, please verify my guess that it is an issue with the background animation by connecting a device and check again. This would also explain why it was fine when you transferred files.

**Comment by schlagmichdoch** [comment]
@MMMZZZZ could you test my hypothesis?

**Comment by schlagmichdoch** [comment]
So I tried a lot: create svgs via javascript and hide/show layers, using css transformations, and creating embedded gifs and videos that loop. All used at least as much CPU + GPU for calculation and displaying.

In the end I could drastically reduce the loads by kind of caching the single animation frames to canvases off screen on the first loop and redrawing them as images after that. This leads to a much lower GPU load. As I also rewrote the animation function to and used a fixes interval the CPU load is lower too ( think🔋 ++).

Could you please test and verify on this instance: https://pairdrop-dev.onrender.com/ that it still works and looks the same but uses less resources?
Then I will merge this :)

**Comment by MMMZZZZ** [comment]
Interesting. Wouldn't have thought that such a simple animation could be so difficult to implement in a power efficient way. But then again, I'm not familiar with web development or animations at all. 

Anyway, it worked. CPU load seems to be down to roughly 3% (about 3W). iGPU load is better as well: percentage is still high-ish with 30-50% but it only takes 0.7-1W. Similar results in MS Edge. 

Thanks a lot!
Max

**Comment by schlagmichdoch** [comment]
Did not think so either but as it is looped every 3 seconds the caching approach is pretty straight forward. I'm just supprised that showing GIFs is pretty GPU expensive for a browser. Especially if there is transperancy involved.

Very glad it worked! This is now merged and live! 🎉

**Comment by schlagmichdoch** [comment]
The following comments were deleted by GitHub (via hubot) as part of [mistakenly marking this account as spam on 17th February 2024](https://github.com/schlagmichdoch/PairDrop/issues/284). The correct thread order and the creation date is unclear. I decided to manually restore them anyway in order to complete the information this issue holds even though the restored information might be outdated:

Comment by @schlagmichdoch:
---

I guess this is related to the way Snapdrop implemented the background animation. I wanted to rewrite the background animation for PairDrop anyway as there seems to be an issue with it getting speed up really fast sometimes.

As the background animation stops as soon as a device is connected, please verify my guess that it is an issue with the background animation by connecting a device and check again. This would also explain why it was fine when you transferred files.
