### ISSUE TITLE
File Handling API not working?

### ISSUE THREAD

**Issue by fm-sys** [schlagmichdoch/PairDrop#83]
I've followed the steps described in https://github.com/schlagmichdoch/PairDrop/blob/master/docs/how-to.md#send-files-directly-from-context-menu-on-windows

However I haven't managed to find a way to actually send a file. How can I trigger the send?

![grafik](https://user-images.githubusercontent.com/64581222/224848861-e7799110-c891-470c-baa6-78ba81bd10b3.png)

**Comment by schlagmichdoch** [comment]
What browser are you using?
For Edge, after setting it up as described in the docs you can right click your test.txt select `Open with` and then `PairDrop`. Then it will look like this:
![Screenshot 2023-03-14 000028](https://user-images.githubusercontent.com/52242352/224851199-e1050049-5fa6-4fc8-842b-fbcaa43a0b66.png)

**Comment by fm-sys** [comment]
Yes, I was using Edge as well. Maybe a device specific issue...? I'll look into the logs if I see anything suspicious

**Comment by schlagmichdoch** [comment]
What version of windows and edge are you using?

**Comment by fm-sys** [comment]
These were the versions where it did not work:

![grafik](https://user-images.githubusercontent.com/64581222/224999900-9f724175-7791-4c1f-b551-d3c7522528f2.png)

![grafik](https://user-images.githubusercontent.com/64581222/225000104-6b6d2358-738c-47f2-b8c4-d0bf947450e5.png)

**Comment by schlagmichdoch** [comment]
I've just tested it with the same Edge version and W11 OS build 22621.1344 so that's probably not the issue. Try deinstalling PairDrop PWA, check whether the edge flag is set correctly and reinstall. Alternatively, Google Chrome or Chromium work too: #17

**Comment by schlagmichdoch** [comment]
Have you tried to use sth like [ungoogled-chromium](https://github.com/ungoogled-software/ungoogled-chromium)? If another browser works that would eliminate a deactivation via registry keys or alike.

**Comment by fm-sys** [comment]
Nor yet. Didn't found time to install yet another browser. But I guess it might indeed be a browser problem (the flag is in alpha state anyway)

**Comment by schlagmichdoch** [comment]
Du could also test the given demo: https://learn.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/handle-files#demo

**Comment by fm-sys** [comment]
The demo does work correctly. But I noticed that the demo correctly registers itself inside the "open with" menu while Pairdrop doesn't...

![grafik](https://user-images.githubusercontent.com/64581222/225650309-dec205f7-c5c4-4416-bc16-9760be0234b7.png)

**Comment by schlagmichdoch** [comment]
I’ll check it again and come back to you. Maybe it’s a problem with PairDrop after all as it should work the same as the demo

**Comment by s1w2a3** [comment]
Hi, I had the same problem with Edge. I tried using Google Chrome (no flag required on latest veersion), and now it's working like a charm. I can even share multiple files at once thanks to the tutorial. Maybe you should try too @fm-sys

**Comment by MrPropre** [comment]
I have the exact same problem. Pairdrop isn't registered into Open With menu and sharing using "Send To" doesn't work

**Comment by schlagmichdoch** [comment]
@MrPropre have you tried using Google Chrome?

**Comment by schlagmichdoch** [comment]
@fm-sys any news? Can I close this issue or does the problem persist?

**Comment by fm-sys** [comment]
After uninstalling pairdrop edge doesn't provide the option to install pairdrop at all anymore. Really weird what's going on there 🤷‍♂️

**Comment by schlagmichdoch** [comment]
This normally only happens when the app is already installed. Are you sure the app is successfully uninstalled? Type in `edge://apps` in the edge url bar to see all installed apps.

**Comment by fm-sys** [comment]
PairDrop is not listed under `edge://apps`. Something is really weird there but I'm quite sure it's not the fault of PairDrop...

**Comment by schlagmichdoch** [comment]
I'm closing this issue because it's stale. Feel free to reopen.

**Comment by schlagmichdoch** [comment]
The following comments were deleted by GitHub (via hubot) as part of [mistakenly marking this account as spam on 17th February 2024](https://github.com/schlagmichdoch/PairDrop/issues/284). The correct thread order and the creation date is unclear. I decided to manually restore them anyway in order to complete the information this issue holds even though the restored information might be outdated:

Comment by @schlagmichdoch:
---

What browser are you using?
For Edge, after setting it up as described in the docs you can right click your test.txt select `Open with` and then `PairDrop`. Then it will look like this:
![Screenshot 2023-03-14 000028](https://user-images.githubusercontent.com/52242352/224851199-e1050049-5fa6-4fc8-842b-fbcaa43a0b66.png)
