### ISSUE TITLE
Enhancement: PWA only works with HTTPS connection

### ISSUE THREAD

**Issue by taha-yassine** [schlagmichdoch/PairDrop#89]
To be able to install the PWA (from whatever platform/browser) from a self-hosted instance, the connection needs to be established through HTTPS (source: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Installable_PWAs). Maybe adding somewhere in the docs (FAQ for example) that setting up an SSL certificate is a requirement for this to work would be helpful. I can submit a PR if approved.

**Comment by schlagmichdoch** [comment]
While this is stated here: https://github.com/schlagmichdoch/PairDrop/blob/master/docs/host-your-own.md#testing-pwa-related-features
I agree, that it should be made more prominent. What do you think about adding some general notes all the way at the top of  host-your-own.md ?

**Comment by taha-yassine** [comment]
I'm sorry I completely missed it. IMHO regarding this particular point, I think the best thing to do is to mention it in the FAQ, because that's where I went to look for when I encountered this problem. Actually there is already an entry regarding PWA installation problems, so that's where I would expect to find the solution. It would only take one or two additional sentences to very briefly explain the root cause and redirect the reader to the section you linked for additional details. What do you think?

**Comment by schlagmichdoch** [comment]
Thanks for your input. I added this to the first FAQ point: https://github.com/schlagmichdoch/PairDrop/blob/master/docs/faq.md#frequently-asked-questions

Does this close your issue?

**Comment by taha-yassine** [comment]
Absolutely, thanks!
