### ISSUE TITLE
Bug: Docker Build Image doesn’t work

### ISSUE THREAD

**Issue by BAUproject** [schlagmichdoch/PairDrop#96]
**Describe the bug**
I pull the code I run. It’s suck in connecting webtrc not found 404
It runs locally fine with npm start

**To Reproduce**
Git clone 

Docker build . -t name

**Desktop (please complete the following information):**
 - OS: Window 10
 - Browser Chrome
 - Version Node 18

**Self-Hosted**
Yes

**Comment by schlagmichdoch** [comment]
Please provide a screenshot or a copy of the logs of the error.

When does the webrtc error occur?
When executing `docker build`?

**Comment by BAUproject** [comment]
Error occurs when trying to visit to web page

**Comment by schlagmichdoch** [comment]
Sorry for the delay!

I just tried to reproduce the error but everything works as expected when using the self built image as documented here:
https://github.com/schlagmichdoch/PairDrop/blob/master/docs/host-your-own.md#docker-image-self-built

Be sure to use `--pull` with your build command to ensure you are using the latest node version and start the application by running `npm run start:prod` inside your docker (see docs above)

**Comment by schlagmichdoch** [comment]
@BAUproject Any news?

**Comment by BAUproject** [comment]
Haven’t texted yet, will do it and update you

**Comment by schlagmichdoch** [comment]
Any news?

**Comment by schlagmichdoch** [comment]
I'm closing this issue because it's stale. Feel free to reopen.
