### ISSUE TITLE
Bug:/Enhancement:/Feature Request: Devices not showing up

### ISSUE THREAD

**Issue by Dec-35** [schlagmichdoch/PairDrop#99]
### **Describe the bug**
When connected to the same local network (windows PC via ethernet, Android phone (using the app) via Wifi and MacBook via Wifi), none of the devices show up. (All of the devices are using pairdrop, not snapdrop)

### **To Reproduce**
1. Open snapdrop on the android phone
2. select pairdrop server
3. go onto window pc and go to pairdrop.net
4. go onto macbook and go to pairdrop.net
5. don't get anything

**Expected behavior**
I expect the UI to show my two other devices that are both connected to the same network as the PC.

### **Screenshots**
*Pairdrop.net (after clicking the pair button and entering the code - wasn't fast enough to catch the error message):*
![image](https://user-images.githubusercontent.com/88966922/230686462-085174d4-d23b-42a5-ae6b-07ac915f8419.png)
*Snapdrop.net :*
![image](https://user-images.githubusercontent.com/88966922/230686519-4819694c-3d6a-4025-b8ec-1c11af0a2d9f.png)

### **Devices**
**Desktop:**
 - OS: **Windows 11** 22H2
 - Browser: Firefox 
 - Version 111.0.1
 
 **Laptop:**
 - OS: **MacOS Ventura Beta 13.4**
 - Browser: Firefox 
 - Version 111.0.1

**Smartphone:**
 - Device: Xiaomi mi 9t Pro
 - OS: **Android 11**
 - Snapdrop App
 - Version 2.0.2

**Self-Hosted**
No

### **Additional context**
When trying to click on the Pair icon and entering the code, I get an error on both devices that "devices are not persistant" and then another icon appears, same as the other one but crossed off.
Then, when doing to snapdrop.net on the browsers (pc and mac) and seting the phone server to snapdrop.net, the devices appear but I can neither send files nor messages.

**Comment by schlagmichdoch** [comment]
> Then, when doing to snapdrop.net on the browsers (pc and mac) and seting the phone server to snapdrop.net, the devices appear but I can neither send files nor messages.

Thanks for including that information, as it confirms that it's the same problem for Snapdrop and PairDrop.
PairDrop does only show devices when the connection is established successfully. This way, whenever a device is shown, sending sth to the device will work.

Your devices must be able to create webrtc connections. You can check here: https://www.webrtc-experiment.com/DetectRTC/#isWebRTCSupported (under Browser Supports WebRTC (Either 1.0 or 1.1)? it must say Yep. Some networks or VPN connections somehow disable all webrtc connections.

Maybe this is also connected to #71 

I have just added a new TURN server to enable sending between devices behind different NATs. Could you please test whether this is still an issue? If so, please open dev tools and provide the console errors that are shown.

**Comment by Dec-35** [comment]
It's fixed! I didn't have to do anything, I just went to pairdrop.net and it worked. All devices show up and I can send files at full speed. Thank's for fixing it! 

It's a great app btw, I really like it! Continue the great work man!

**Comment by schlagmichdoch** [comment]
Glad to here this fixed your issue!
